### ISSUE TITLE
[FEATURE] Copy-to-clipboard component

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1006]
**18/07/2022 Reopened - see [comment below](https://github.com/IDEMSInternational/parenting-app-ui/issues/1006#issuecomment-1187596203)**

**What?**
A new component _select_text_ (i.e. the _type_ in the spreadsheet) to display a text and a copy-to-clipboard button (with an icon _copy_icon_ or a text _copy_text_). When the copy-to-clipboard button is clicked, the text input in the _value_ column is copied to the clipboard, and the button is replaced by the text _copied_text_ or an icon _copied_icon_. As usual, icons should be coming from the [plh_assets](https://drive.google.com/drive/folders/1dp9QAQ84m8pm0IBQTSPXe1ramyynKPNn) folder on the Google Drive, or from the icon library [Ionicons](https://ionic.io/ionicons). 

**Why?**
With this feature, users can more easily copy their UUID from the template [user_code](https://docs.google.com/spreadsheets/d/1yb7SP-W-uOvxDRELlLJEDPwPFE9H1GtEHsn2_sVZtAs/edit#gid=1384726662) (currently they are taking a screenshot of the page).

![image](https://user-images.githubusercontent.com/74557272/132379930-ffcc88d9-f2d7-40e6-8ff3-0aa9b0f9067c.png)

**How?**
Syntax proposed in template [feature_select_text](https://docs.google.com/spreadsheets/d/1MX-sy4RLy7xPkl0vHZ0lfp-kzGWyohViWjNhyGn7Vts/edit#gid=1254547698).
![image](https://user-images.githubusercontent.com/74557272/132382318-e31ee0a9-8f7b-4a89-8942-998fdace0141.png)

**Other details**
I'm thinking of something like this 
![react-copy-to-clipboard-demo2](https://user-images.githubusercontent.com/74557272/132379592-8f28418f-79ed-45b7-b406-810fa1595776.gif)
There's no design for this component. I'd suggest the text and button appear in a dashed box with look-and-feel similar to the display_group style _dashed_box_. For user-friendliness it would be good if the clickable button is not just an icon, but actually looks like a button (e.g. has a drop-shadow).

**Comment by zulkifelff** [comment]
Creating a PR for this feature soon. Just to be clear from an implementation point of view, does only the message in key '**value**' needed to be copied?

**Comment by EsmeeIDEMS** [comment]
> Creating a PR for this feature soon. Just to be clear from an implementation point of view, does only the message in key '**value**' needed to be copied?

Yes, the message in **value** should be copied. If it depends on any variables, it should be first evaluated and then copied (i.e. the copied text never contains any @calc / @global / @local / @fields.
