### ISSUE TITLE
[BUG] Radio button size improvements

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1014]
**Describe the bug**
- [ ] The size of the buttons in a radio group changes depending on whether or not the parameter options_per_row is given. Desired behaviour: A set of _n_ radio buttons that fit on one row should not change if parameter options_per_row is set to _n_. 
- [ ] Radio buttons should increase in size to fit the text. 

**App version**
v0.11.2

**To Reproduce**
Open debug template. 

**Debug Template**
[debug_radio_group_size](https://docs.google.com/spreadsheets/d/1pSFFOv9B9x0oUSuSJDp6RNePJ1XSP6yVSjXA8jzBclQ/edit#gid=481972108)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/132690414-19fd9248-1607-42e6-9648-1c839b6eea15.png)

**Comment by esmeetewinkel** [comment]
Someone picked up this issue when reviewing the Swahili version of the app

<img width="644" alt="image" src="https://user-images.githubusercontent.com/74557272/225121774-5a2c8acd-ccd4-4d2e-8fae-4a746d2a4633.png">

**Comment by chrismclarke** [comment]
For the text sizing, given the two options which would be your preference @esmeetewinkel 

A) The button resizes to fit all text, buttons alongside also resize to keep consistent
B) The button resizes to fit up to x lines of text, at which point the text in the button becomes scrollable to view more

I assume probably (A) is the preferred behaviour for now as it covers all simple use-cases, and the (B) could be an add-on (with some authoring option to specify `line-clamp` settings, i.e. max lines to show

**Comment by esmeetewinkel** [comment]
> For the text sizing, given the two options which would be your preference @esmeetewinkel
> 
> A) The button resizes to fit all text, buttons alongside also resize to keep consistent B) The button resizes to fit up to x lines of text, at which point the text in the button becomes scrollable to view more
> 
> I assume probably (A) is the preferred behaviour for now as it covers all simple use-cases, and the (B) could be an add-on (with some authoring option to specify `line-clamp` settings, i.e. max lines to show

No strong preference, happy to go with (A) - I think scrolling on a clickable component is not desirable. Large texts will be awkward anyway so will try to avoid from the authoring side where I can.
