### ISSUE TITLE
[FEATURE] Parameter for radio groups to match image heights

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1015]
**What?**
For the tile_component there is a particular style _workshop_page_ that achieves the display of the individual/together tiles in the accordion items on the Weekly Workshop page. There should be a similar display for radio groups, to be used in the Weekly Workshop Options.  

**Why?**
One of the two images is a "portrait" and the other is "landscape". In the default display, the landscape image appears too small.

**How?**
A parameter, e.g. _match_image_heights_, that is false by default and can be set to true in the parameter list of a radio group.

**Templates**
[workshop_accordion_item](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=909694533)
![image](https://user-images.githubusercontent.com/74557272/132718946-2199964e-c444-46c5-8df6-9966d4fce813.png)
[workshop_options_page](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=1204310080)
![image](https://user-images.githubusercontent.com/74557272/132719012-58fe35b6-08a2-4590-be92-8d195a68621b.png)

**Debug template**
[debug_radio_group_image_scale](https://docs.google.com/spreadsheets/d/1pSFFOv9B9x0oUSuSJDp6RNePJ1XSP6yVSjXA8jzBclQ/edit#gid=384133700)
![image](https://user-images.githubusercontent.com/74557272/132718484-87510dd1-eb2f-433b-8f50-55d8ece714cd.png)

**Additional comments**
I'm not sure how the image sizing in the tile style _workshop_page_ is managed, but if it's just matching the image heights in a similar way, possibly we should rename this parameter to agree with the one for radio groups.

**Comment by thisishamza** [comment]
@EsmeeIDEMS 
For these specific pages, radio groups looks like this on the web.

[workshop_options_page](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=1204310080)
![workshop_options_page_before_web](https://user-images.githubusercontent.com/62892109/141253557-41b3eba5-19ac-4b2c-9e4e-60eafb68f04b.png)

[debug_radio_group_image_scale](https://docs.google.com/spreadsheets/d/1pSFFOv9B9x0oUSuSJDp6RNePJ1XSP6yVSjXA8jzBclQ/edit#gid=384133700)
![debug_radio_group_image_scale_before](https://user-images.githubusercontent.com/62892109/141254365-7d4847f5-4222-4d6b-861c-35898f3f7bf9.png)

Do we need to work on this too?

**Comment by EsmeeIDEMS** [comment]
Yes, please! Would be great if (in the screenshot of debug_radio_group_image_scale you attached) the radio group text and image could be sized similar to the tile text and image.

**Comment by esmeetewinkel** [comment]
Closed with https://github.com/IDEMSInternational/parenting-app-ui/pull/1848
