### ISSUE TITLE
[BUG] Tour positioning is off when launched through start_tour action

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1026]
**Describe the bug**
When a tour is launched using the start_tour action, the tour elements that are associated to an element on the page are all positioned in the top-left corner of the screen. 

**App version**
v0.11.2

**To Reproduce**
Launch debug_tour from the tour list [http://localhost:4200/tour](http://localhost:4200/tour) and see it works fine.
Then launch debug_tour by launching the template debug_tour_template and clicking the button. Tour elements are positioned in the top left corner of the screen. 

**Debug Template and Tour**
[debug_tour_template](https://docs.google.com/spreadsheets/d/1CQzsurOr4egC706cx_Fvkk5Zfvl-vRmd-Pu40mYM1qA/edit#gid=1916689711) and [debug_tour](https://docs.google.com/spreadsheets/d/1CQzsurOr4egC706cx_Fvkk5Zfvl-vRmd-Pu40mYM1qA/edit#gid=95491335)

**Screenshots and videos**

https://user-images.githubusercontent.com/74557272/133436732-6d9aef9c-65b4-4859-bddf-65740fad3b8c.mp4

**Comment by chrismclarke** [comment]
Think likely reason is due to duplicate home pages (although tour code could also do with a bit of a tidy)
Will test again once merged #1021

**Comment by chrismclarke** [comment]
I think this was fixed with the home page fixes.

https://user-images.githubusercontent.com/10515065/149386916-e86244d2-a1be-4b59-b653-2a25d6397ee0.mp4


@EsmeeIDEMS - are you happy to close?
