### ISSUE TITLE
Blank translation should be replaced by English

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1034]
**Details**
Blank translation in the .json file from_translators should be replaced by English (SourceText) in the app.

**Description using an example**
Crowdin adds English strings that don't yet have a translation to the .po file as 
#. type=template
msgctxt "template"
msgid "Notifications"
msgstr ""

The conversion script to .json converts this item into 
  {
    "SourceText": "Notifications",
    "text": "",
    "type": "template",
    "note": ""
  },

This currently gets recognised in the app as a blank translation. In the example of "Notifications" this results in a button without button text.
![image](https://user-images.githubusercontent.com/74557272/134145898-c0f96e09-78d3-4d8c-84e6-52735fd65a01.png)

**Comment**
This issue could be dealt with on any level, but @dannyparsons suggested it might be best to do this in the app.

**Comment by EsmeeIDEMS** [comment]
I've uploaded these translation files to the branch update_translations

**Comment by ChrisMarsh82** [comment]
@chrismclarke has this already been completed?

**Comment by chrismclarke** [comment]
@ChrisMarsh82 
I think Esmee found a workaround/partial solution changing some of the export options from crowdin, I haven't touched the codebase though so still will likely be sensible to apply a small fix for this. I have this issue around 3/4 on my priority list currently, so hopefully will come to it by early next week

**Comment by EsmeeIDEMS** [comment]
Closing this as it is no longer required (the current Crowdin settings prevent this from ever happening)
