### ISSUE TITLE
[BUG] Receive dozen of notifications each time the local app is launched

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1045]
**Describe the bug**
When running the app (or refreshing [http://localhost:4200/home](http://localhost:4200/home) in the browser window), about 12 notifications are sent. I'm not sure what causes this, if this was to be expected and whether this would also happen in the play store app?

**App version**
v0.11.3 

**To Reproduce**
Run app on local device. 

**Screenshots and videos**
https://user-images.githubusercontent.com/74557272/136411280-310307f1-8133-4f2e-ac12-4a6df78bbabd.mp4

**Comment by chrismclarke** [comment]
Fixed with #1098 and #1103
