### ISSUE TITLE
[BUG] Too much space between paragraphs of text and between components

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1050]
**Describe the bug**
There is too much vertical blank space between two paragraphs of text. Also there is too much space around a dashed box. There may be other cases where there is too much white space, in particular, see also issue #1051 

**App version**
v0.11.3 + some merged PRs.

**To Reproduce**
Launch debug templates.

**Debug Template**
[debug_text_paragraphs
](https://docs.google.com/spreadsheets/d/1A159jPS8rSDnA2GDUTda6xeC_Kyu3oYk_-KbuhzMqmQ/edit#gid=1342264693)[feature_dg_dashed_box](https://docs.google.com/spreadsheets/d/1wZ9ez-mQtI5crEIj83dL-iaXhj9J939E9F569nFzTA4/edit#gid=1254547698)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/136756709-88439a0f-cfe0-45d8-bdd8-7c23ac9e4496.png)![image](https://user-images.githubusercontent.com/74557272/136755542-be970780-c400-4587-9a03-0877ac75c4ae.png)

**Comment by chrismclarke** [comment]
closed in #1131

**Comment by EsmeeIDEMS** [comment]
There still seems to be a bit of redundant white space around/above a dashed box. Template [feature_dashed_box](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=42746871)
![image](https://user-images.githubusercontent.com/74557272/147065015-1521596c-dde8-47a1-a555-eba1bc4130a4.png)

**Comment by chrismclarke** [comment]
Perfect, more hardcoded margins I can get rid of :D (just done)

![image](https://user-images.githubusercontent.com/10515065/147104535-58a05f5e-559b-4037-8221-a7458a7d9691.png)
