### ISSUE TITLE
Forbid use of hyphen in variables 

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1059]
**Details**
In certain languages, the text in a variable (global, field, local) will be connected to other text by a hyphen. We should maybe consider to forbid using hyphens in variable names, and add _hyphen_ to the list of characters that indicate the end of a variable (just like _space_ and _full stop_).

**Example from Afrikaans translation**
 {
    "SourceText": "@global.weekly_workshops quick start",
    "text": "@global.weekly_workshops-kitsbegin",
    "type": "tour",
    "note": "The string @global.weekly_workshops should not be translated."
  },

**Comment by ChrisMarsh82** [comment]
Use double character symbol to define the end of variable - possible /\ or \/ or @#

**Comment by ChrisMarsh82** [comment]
Another possibility @<variable_name>  e.g. @<global.weekly_workshops> 
Old syntax should still work.

**Comment by chrismclarke** [comment]
I would LOOOVE string templating/encapsulation, at various times I've suggested some common options, from popular JavaScript frameworks e.g.
 `{@local.some_value}-not parsed`
 `{{@local.some_value}}-not parsed`
 
 However I think the decision was made against to retain more compatibility with rapidpro. Nonetheless it's been a major challenge to get working with the complex data patterns we end up with. A few real-world examples that I've picked up on that now form the base of my testing include:
 ```
    * `hello @local.some_name`
   * `!@local.some_field`
   * `@local.val_1 - @local.val_2` (in case of numbers perform subtracation)
   * `@local.val_1 - @local.val_2` (in case of text show with dash)
   * `pick_random(@local.some_list)`
   * `Math.max(@local.val_1,@local.val_2)`
   * `@local.field_that_returns_json.nestedfield.deeperNest`
   * `@local.@local.dynamic_field_selector`
 ```
 The list goes on...
 Mostly my strategy revolves around creating a local context of known evaluations, e.g. 
 `@local.some_field` => `this.local.some_field` 
 and assigning 
 `this.local = {some_field:'parsed value'}`
With the full set of local, global (and any other namespaced variables) defined, I then just try to evaluate in javascript. This handles cases like `this.local.val1 - this.local.val2` if numbers, and then for expressions that throw errors (like the case where val1 and val2 are strings), it makes a direct text replacement, before trying to re-evaluate again (in case where further dynamic expressions exist). Overall quite complex and messy!
 
 I like your suggestion of encapsulating inside of the `@` symbol, although not sure how well it will deal with some of the advanced multi-expression cases (I guess pretty well if we allow for recursive nesting within and work inside-out)

**Comment by chrismclarke** [comment]
Agreed the dashes are problematic (if for no other reason the fact they are also subtraction operators!). 

As it happens the parser should already be ignoring them.

Code that handles dynamic text extraction:
https://github.com/IDEMSInternational/parenting-app-ui/blob/master/src/app/shared/utils/variables.utils.ts#L12

Specific regex pattern
```
/[`!]?@([a-z]+)\.([0-9a-z_]+)([0-9a-z_.]*)/gi;
```

Here's a link to test the regex online:
https://regexr.com/69a5d

![image](https://user-images.githubusercontent.com/10515065/141230808-dbb89532-b990-4393-a078-a95ae81f7af8.png)

If that's not working as expected let me know and I can try deeper dive

**Comment by EsmeeIDEMS** [comment]
> Agreed the dashes are problematic (if for no other reason the fact they are also subtraction operators!).
> 
> As it happens the parser should already be ignoring them.
> 
> Code that handles dynamic text extraction: https://github.com/IDEMSInternational/parenting-app-ui/blob/master/src/app/shared/utils/variables.utils.ts#L12
> 
> Specific regex pattern
> 
> ```
> /[`!]?@([a-z]+)\.([0-9a-z_]+)([0-9a-z_.]*)/gi;
> ```
> 
> Here's a link to test the regex online: https://regexr.com/69a5d
> 
> ![image](https://user-images.githubusercontent.com/10515065/141230808-dbb89532-b990-4393-a078-a95ae81f7af8.png)
> 
> If that's not working as expected let me know and I can try deeper dive

Thanks. This seems to be working as expected in the setting of templates (tested in the template [debug_translation_hyphen](https://docs.google.com/spreadsheets/d/1Bwh8eb2B43AAlDND4q0b4E-EXgnd6IRjmIFIf1Jbk1c/edit#gid=1307302086), by setting app language to za-af).

This is not working in the setting of tours. See screen video below and the sheet [debug_tour_translation](https://docs.google.com/spreadsheets/d/1CQzsurOr4egC706cx_Fvkk5Zfvl-vRmd-Pu40mYM1qA/edit#gid=554099668).

https://user-images.githubusercontent.com/74557272/142439555-a2b3244e-3e9a-4747-a2e7-1cd14265366b.mp4
