### ISSUE TITLE
Improve how goals service and components share data updates

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#109]
Currently, the data structures are too top-down - all data is loaded on intialisation and everything has to be fully refreshed when a task is marked as complete. Ideally want to be able to apply incremental updates and see component changes without heavy reload or re-rendering

**Comment by michaelclapham** [comment]
@chrismclarke Is this issue still relevant?

**Comment by chrismclarke** [comment]
I'm not sure, I think tasks/goals/reminders is on hold until templating figured out and we start to implement some of those features in the templates. I think if we do need to revisit this the issue will be pretty obvious so happy to close for now and open another in the future.
