### ISSUE TITLE
Remove hardcoded startup and menu pages 

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1114]
**Details**

- [x] The hardcoded About, Terms and conditions, Privacy policy and `analytics.survey.html` pages should be deleted as they have been replaced by templates. 
- [x] The reference to `analytics.survey.html` in the startup sequence (I believe in `home.spec.ts`) needs to be replaced by a reference to the template [accept_terms](https://docs.google.com/spreadsheets/d/1MJzzdTYDZg0VkS5zxrXY4lKV5Oi954pw1sIVJUOOzWM/edit#gid=1884781962). 
- [x] The asset `src\assets\images\privacy-policy.svg` can be deleted, since it is now uploaded to the Google Drive [here](https://drive.google.com/file/d/1mDThp4VXDioUE4boMmsBaCf9JTUewS0p/view?usp=sharing). 
- [x] Add a redirect so that the URL /privacy displays the template [app_menu_privacy_policy](https://docs.google.com/spreadsheets/d/1NUCgonMc3K4y9bFjYH7LjquRZyiIN2AappLP_0mlH5Q/edit#gid=484038577). This is to ensure that the link to the Privacy Policy in the Google Play Console keeps working. 

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/145221559-0621e76a-e51a-42a7-84ef-e338afdcf768.png)
![image](https://user-images.githubusercontent.com/74557272/145223292-f28dc319-6020-4c97-84de-4878e0215b24.png)

**Comment by EsmeeIDEMS** [comment]
This issue overlaps with #929

**Comment by chrismclarke** [comment]
Privacy link fixed in #1112

**Comment by chrismclarke** [comment]
All issues fixed in #1112, will close from there once merged
