### ISSUE TITLE
[FEATURE] Accordion component

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1115]
**What?**
An accordion component, where each section can contain components and/or nested templates. 

**Design**
Figma illustration from graphic designer:
![image](https://user-images.githubusercontent.com/74557272/145228048-b1cfcde2-1f86-4840-a791-d2fa4e5352f3.png)
(Developers can propose a design with similar look-and-feel)

**How?**
Proposed spreadsheet authoring syntax in the template [example_accordion](https://docs.google.com/spreadsheets/d/1gfnWmr59DF0ZsuSuBh0K1o9fMqEg-z6Qa7eJNsiB-rQ/edit#gid=63099847). This syntax is an adaptation/simplification of the existing syntax used for the component workshop_accordion, as demonstrated in the template [example_workshop_accordion](https://docs.google.com/spreadsheets/d/1gfnWmr59DF0ZsuSuBh0K1o9fMqEg-z6Qa7eJNsiB-rQ/edit#gid=1595229908).

**Comment by chrismclarke** [comment]
Discussed briefly on call, hopefully can be reworked with code from existing workshops accordion

**Comment by chrismclarke** [comment]
Another possibility, is that ionic recently released their own accordion component that could be used:
https://ionicframework.com/docs/api/accordion

Would require updating ionic 5 -> 6 (likely going to want to do eventually, but will just depend on priorities)
