### ISSUE TITLE
[BUG] Icons in audio player and timer are off-centre

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1118]
**Describe the bug**

- [ ] Audio player: play/pause icons are not centred
- [ ] Timer: play and "+1" icons are not centred

**App version**
v0.12.5

**Debug Template**
[feature_timer](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1812549948)
[feature_audio](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=551506513)

**Screenshots and videos**
<img width="161" alt="image" src="https://user-images.githubusercontent.com/74557272/145609847-d1e5cfe1-1708-4848-8ab9-11d45ebd048d.png">
<img width="166" alt="image" src="https://user-images.githubusercontent.com/74557272/145609763-3ffbe798-0fc7-45fd-89fc-d4dc6fdd5b4e.png">
<img width="162" alt="image" src="https://user-images.githubusercontent.com/74557272/145609954-f412e38d-ab00-4cff-9516-0da4f72c06c4.png">
<img width="160" alt="image" src="https://user-images.githubusercontent.com/74557272/145610108-bbd41fbb-7ff4-4585-b5a6-115e570c0f66.png">

**Comment by chrismclarke** [comment]
Not sure why but there seems to be a 5px offset hardcoded for all the icons in the component, I'll fix and include in #1142
