### ISSUE TITLE
[BUG] Buttons/tiles horizontal padding

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1121]
**Describe the bug**
Buttons and tiles need to have the same width. Multiple buttons or tiles that appear side-by-side need to have same _total_ width as single button or tile. Currently it seems that they have some padding on the outside, which results them being narrower. 

**App version**
v0.12.5

**Example Template**
[example_buttons_padding](https://docs.google.com/spreadsheets/d/1yhYINwRZvDfj9_LZyBHrIKsz8mkDTeS28gXnabCzUqI/edit#gid=1595229908)
![image](https://user-images.githubusercontent.com/74557272/145818947-8ae307a0-437b-487b-a33e-e947ecfc6b12.png)

**Template Name**
[parent_centre_relax_and_act](https://docs.google.com/spreadsheets/d/1N8ObxOpDZv_dtzrYu16OyOfpkTK_HsuPAZPPXXCnZpk/edit#gid=1601005206)

**App screenshots**
<img width="630" alt="image" src="https://user-images.githubusercontent.com/74557272/145791789-5a7c1c0d-e0af-4b92-b6b5-752dde76ca5b.png">

**Figma image**
![image](https://user-images.githubusercontent.com/74557272/145791906-14f3902c-1aa3-44d1-9e24-7397fc5fd74b.png)

**Comment by chrismclarke** [comment]
I think worse than the confusing extra padding, is the arbitrary max widths which means at different screen size things start to look very messy too.
![image](https://user-images.githubusercontent.com/10515065/146366139-7ec6fbb2-5085-4ed5-9be7-8ecfe7b029d1.png)

I've just taken a quick look at the style code and it's really confusing, so I'll try resolve myself first but may require a slightly larger overhaul somewhere down the line

**Comment by chrismclarke** [comment]
closed with #1131
