### ISSUE TITLE
[BUG] Text should stay within radio buttons in language select template

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1128]
**Describe the bug**
In the template [language_select](https://docs.google.com/spreadsheets/d/1iSG1kzK4OTHcoiwWoZ25LZxrJqERg2_iP9369HTi_bQ/edit#gid=823624970) (one of the first screens a user sees after installing the app) the language names should stay within the radio buttons. 

**App version**
v0.12.5 

**Template Name**
[language_select](https://docs.google.com/spreadsheets/d/1iSG1kzK4OTHcoiwWoZ25LZxrJqERg2_iP9369HTi_bQ/edit#gid=823624970)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/146370297-f0f4995f-7754-46e5-beb5-7bfed2c54de9.png)

**Additional context**
Text should always fit inside radio buttons, not just in this instance. See issue #1014.

**Comment by chrismclarke** [comment]
closed with #1131
