### ISSUE TITLE
[BUG] Image in tile gets cropped

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1162]
**Describe the bug**
In some (reasonable, e.g. iPhone SE) screen dimensions, some images displayed on tiles get cropped. 

**App version**
v0.13.0 

**Template Name**
[weekly_workshops](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=1277645488)

**Debug Template**
[debug_dg_tile_button](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit#gid=692769484
)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/148759354-3b9690e8-16a4-4e97-98ea-feefff493400.png)
![image](https://user-images.githubusercontent.com/74557272/148759002-e9b13fcd-3657-4b78-8323-80274058f39f.png)

**Comment by chrismclarke** [comment]
Yeah, there's a horrible amount of hardcoded styles for these with very specific changes for different screen sizes. Another candidate for an overhaul for sure!
![image](https://user-images.githubusercontent.com/10515065/149437124-fa74457b-e0b3-4ce2-8713-4ac0dc9af469.png)

But until such a time I think I can find some simple fixes to tidy up the height issue
