### ISSUE TITLE
[BUG] Too much padding around banners

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1175]
**Describe the bug**
Too much padding around `banner_short` display group.

**App version**
v0.13.0

**Screenshots** 
![image](https://user-images.githubusercontent.com/74557272/149806071-e6c26f38-722a-413f-820e-579ea6ba1a4d.png)
![image](https://user-images.githubusercontent.com/74557272/149806267-c65d47d3-5b26-4294-8245-8e69165856c8.png)

**Template Name**
[banner](https://docs.google.com/spreadsheets/d/1ZkAXSGDgCQrDMUbyVVgJrdMUTnuZOicvecP6qytA9sY/edit#gid=57567680)

**Comment by chrismclarke** [comment]
These are hardcoded values so I can make any arbitrary adjustments (will use my judgement and send in a PR)

Another minor side issue is that there will always be additional padding at the start of the [box_radio_buttons_emo_temp](https://docs.google.com/spreadsheets/d/1NrMPEVnn_misvqrKzxvRLY3PN0-dg1yc4rhiedSiss8/edit#gid=1596570145) template as there are 2 text fields which contain no text (assume designed to be populated dynamically).

A better solution might be to store the `text` and `question_text` fields as variable (set_field) and conditionally show the text row (e.g. rename `question_text_display` or similar) when the text or question_text field has been set. Although this is only a single line spacing that we are talking about

![image](https://user-images.githubusercontent.com/10515065/150851893-d42386ca-5959-4304-9275-e621d2f3534a.png)

![image](https://user-images.githubusercontent.com/10515065/150851831-78e30c19-086c-4e35-8d97-4aeef2905753.png)
