### ISSUE TITLE
[BUG] ParentPoints page tile scaling

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1181]
**Describe the bug**
The tiles on the ParentPoints page don't scale sensibly. 
- Currently it seems that the font size decreases infinitely. Instead there should be a minimal font size.
- Currently it seems that the minimum width for a tile is very small. Rather than keeping on shrinking the tiles to fit two side-by-side, the default behaviour should be to fall back to just having a single column. 
- Currently, once the app does decide to display all tiles in a single column, the tiles still take up only a small proportion of the width of the screen. Instead the tiles should possibly use the full screen width, to improve legibility. 

**App version**
v0.13.0

**Screen video**

https://user-images.githubusercontent.com/74557272/149977524-d478567c-7a3a-47dd-afd6-925b18294231.mp4

**Additional context**
This relates to issue #1179. Since this page is very central to the app I'm creating this issue dedicated to just improving this page.

**Comment by esmeetewinkel** [comment]
Also there are screen widths for which the tiles overlap 

<img width="198" alt="image" src="https://user-images.githubusercontent.com/74557272/229784511-81b32114-542c-4486-a406-d3ad9e526d9e.png">

**Comment by chrismclarke** [comment]
The parent points items are a bit of a legacy/custom component that we've never really reworked. I can take a quick look to see if there's a simple fix, but longer term we should probably think about removing the custom `parent_point_box` component and find a better way to author with standard display group/grid-based components
