### ISSUE TITLE
Changes to make for creating a new deployment

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1237]
When creating a new deployment of the app, in addition to [creating a config file](https://idemsinternational.github.io/parenting-app-ui/developers/deployments/), the following files need to be updated:

## App ID and name
1. **File path**  
`capacitor.config.ts`
**What to edit** 
`appId` (row 7), `appName` (row 8)

2. **File path**  
`android\app\src\main\assets\capacitor.config.json`
**What to edit** 
`appId` (row 2), `appName` (rows 3)

3.  **File path**  
`android\app\src\main\res\values\strings.xml`
**What to edit** 
`app_name`, `title_activity_main`, `package_name`, `custom_url_scheme` (rows 3-6)

4.  **File path**  
`android\app\src\main\AndroidManifest.xml`
**What to edit** 
`package` (row 3), `android:name` (row 15)

5.  **File path**  
`android\app\src\main\java\international\idems\plh_teens\MainActivity.java`
**What to edit** 
`package` (row 1)
replace `plh_teens` in file path

6.  **File path**  
`android\app\build.gradle`
**What to edit** 
`applicationId` (row 6)
If version number has changed:
`versionCode` (row 10)
`versionName` (row 11)

## App header and side menu
**File path** 
`packages\data-models\constants.ts`
**What to edit** 
- Landing page: `home_path` (row 60), `fallback_path` (row 62)
- Main app header: `title` in `APP_HEADER_DEFAULTS` (row 77)
- Side menu header: `title` in `APP_SIDEMENU_DEFAULTS` (row 90)
- Side menu template: `template_name` in `APP_SIDEMENU_DEFAULTS` (row 92)

**Comment by EsmeeIDEMS** [comment]
Could some of this information be coming from app_config sheets?

**Comment by chrismclarke** [comment]
Really handy to have all this in one place, yes I think ideally we can add info to the config itself to automatically update these files once #1210 is merged.

**Comment by chrismclarke** [comment]
We should add to this recent updates to the config files to override things like languages, menu etc.

**Comment by esmeetewinkel** [comment]
Browser tab title is updated automatically to agree with the main app header - PR https://github.com/IDEMSInternational/parenting-app-ui/pull/1769

**Comment by esmeetewinkel** [comment]
Also need to add the new app ID to firebase, download the `google-services.json` file from there and copy its contents into the `GOOGLE_SERVICES_JSON` GitHub secret. See [SLACK thread](https://idems-international.slack.com/archives/C02AL66MW6T/p1677669757793609). 

![image](https://user-images.githubusercontent.com/74557272/222145078-0e0a804c-3b60-493b-885b-aec2aaf2759b.png)

![image](https://user-images.githubusercontent.com/74557272/222145057-fdc0f502-0d73-48d8-977e-ed67b5371129.png)
