### ISSUE TITLE
[FEATURE] Markdown in notifications does not work

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1249]
**Describe the bug**
Markdown in notifications does not work. In particular I'm using `**This text should be bold** `.

**App version**
v0.14.2

**Screenshots and videos**
<img width="294" alt="image" src="https://user-images.githubusercontent.com/74557272/154716464-3cbb8360-f86b-471f-b964-2d73373a8798.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/74557272/154717201-f71bd5f5-4b03-4861-9aed-7b3f14b6ed9a.png">

**Comment by chrismclarke** [comment]
@EsmeeIDEMS 
I just tried converting the markdown to HTML to see if that would render properly but no luck unfortunately
![image](https://user-images.githubusercontent.com/10515065/157771266-4ff32635-f490-47b0-9abe-0126f38ace18.png)


== sidenote ==
the best way to test this currently is by marking as released the schedule [nf_schedule_in_week_messages](https://docs.google.com/spreadsheets/d/1JXb0lzz8Hztl6K4_3zaUpYrpq9XJjTO7YRPAsx03F-4/edit#gid=119742399) - although adding a new debug should also be quick/easy

Render method applied to branch [feat/notification-markdown](https://github.com/IDEMSInternational/parenting-app-ui/tree/feat/notification-markdown)

**Comment by chrismclarke** [comment]
A few unreplied forum issues suggest this might not be supported:
https://forum.ionicframework.com/search?q=html%20notification

A blog post suggests there are ways to do this in android (https://itnext.io/android-notification-styling-cc6b0bb86021), however looking at the capacitor notification [codebase](https://github.dev/ionic-team/capacitor-plugins) it doesn't appear that any such methods are in use - so I think there is nothing we can do about this for now.
