### ISSUE TITLE
[FEATURE] Data list overrides

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1266]
**What?**

- [x] Longer term ideally we want a system where anything (including data lists) can be overwritten at runtime, however it will only make sense to implement once we have a single system that handles loading data (otherwise it means a lot of copy-paste for templates, data lists, and any other flow type). This is part of what is proposed with other issues related to integrating json instead of ts files

- [x] Additionally, because these datalists are statically defined we could also integrate a system that replaces files during compile so that only the relevant datalist ever makes it into the app. This would be quite easy to do once we've integrated pr #1210 (moved to #2081)

**Other details**
See also issue #1261

**Comment by esmeetewinkel** [comment]
@chrismclarke Can we close this considering the work that went in on data items, or would you say this is something different?

**Comment by chrismclarke** [comment]
I think it might still make sense to have long term so that data lists can be overridden in the same way that templates are (e.g. theme/language-dependent data lists, instead of relying on templates to know all the variations). So I'd say keep open for now, but low priority

**Comment by jfmcquade** [comment]
@ChrisMarsh82 @esmeetewinkel This relates to your discussion

**Comment by ChrisMarsh82** [comment]
@chrismclarke How difficult would this be to do? I was hoping for the facilitator to have all the same templates but have overwritten data_lists for each deployment.

**Comment by chrismclarke** [comment]
I tried giving a quick go in #2040, although a few extra threads started to unravel and I didn't have time to finish. Will keep you updated as I progress (would guess about a half day's work if I can find the time)

**Comment by chrismclarke** [comment]
As a quick update most of the backend code is in place, however the frontend code is a bit more tricky as most of the logic that handles dynamic variables (e.g. `@field.some_field`) is tightly coupled with the templating system and requires significant refactor to generalise. 

I've started work on the refactor and things seem to be mostly working, however will likely wait until more of the current backlog of PRs is merged as quite prone to conflict (particularly #2019, #2035 and #2041)

**Comment by chrismclarke** [comment]
Close first point with #2040 and move second to #2081
