### ISSUE TITLE
How to center an image component?

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1268]
**Details**
How to author from the spreadsheets that an image component should be centered? I thought this could be achieved via 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/74557272/157466556-7d7bd693-631e-4403-b7f8-d851446637f8.png">
but this does not work - it seems that `width` does not get interpreted. 

At the moment the syntax 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/74557272/157466861-1482d807-8bf1-48f8-91ea-7844b7ed9b4c.png">
DOES achieve a centered image of the correct width, but this does not seem the right way to do this. 

**Debug_template**
[debug_dg_center](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit#gid=232108595)

**Screenshot**
<img width="276" alt="image" src="https://user-images.githubusercontent.com/74557272/158341677-f7ec9ece-8866-4465-91ca-b5b48423b87b.png">

**Comment by chrismclarke** [comment]
I've added various comments to the sheet and don't think any additional development work required. If all looks good to you @EsmeeIDEMS  feel free to close here
