### ISSUE TITLE
[BUG] App takes long time to open on TECNO ITEL AC13 phones

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1283]
**Describe the bug**
Testers observed that the TECNO ITEL AC13 smartphones take a significant time to open the app (the screen recording below shows 22 seconds from clicking the icon to having a fully rendered home screen, but the testers reported a case of it taking 3 minutes). 

The splash screen appears immediately, but then it disappears and for 8 seconds the screen is white. After that the screen turns light blue, and the home screen renders. Once the app is open, templates render at a reasonable speed. 

Would it be possible to display something during this wait time to indicate to users that something is happening? 

**App version**
v0.14.2 (Play Store release `international.idems.plh_teens`) 

**Screenshots and videos**
Here's a screen video taken on a TECNO ITEL AC13 phone. Opening the app takes 22 seconds (the app icon is pressed at 0:04 and the home screen is fully rendered at 0:26). The screen is white from 0:09 to 0:17. 

https://user-images.githubusercontent.com/74557272/159519303-beecb052-6e19-4faf-ad76-d7d5c0f44bc4.mp4

**Additional context**
For reference here's a screen video taken on a 5yo high end smartphone, in which opening the app takes 8 seconds. 

https://user-images.githubusercontent.com/74557272/159518787-dc80db67-2823-426f-8d87-a357697d7000.mp4

**Comment by EsmeeIDEMS** [comment]
Just noticed the Play Console pre-launch report picked up on slow rendering as well.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/74557272/160607389-09e97c37-9b09-4e04-91b5-9f0944c9eab2.png">

**Comment by chrismclarke** [comment]
Thanks for the recordings, really handy. I expect the act of running the recording software probably also slows the device down somewhat, but would still be good to improve on this. 

The white-screen delay is when the app is running all its start-up logic. I think there might be some short term gains to be had just by letting the splash screen stay up a little longer (it's meant to autohide after 3s, although it seems to stay a bit longer already anyway) and trying to reduce the number of scripts run on startup

The blue-screen delay is more down to the rendering of templates themselves, and so this is a harder one to improve on without larger changes to how template data is retrieved and displayed. 

As for the performance reports - nice to have although I expect they will be slightly misleading as any startup goes into the various splash screen and logo images page and not the main app screen so it's hard to know exactly what it is measuring.
