### ISSUE TITLE
[BUG] Items in combination with local variables

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1361]
**Describe the bug**
Two specific occasions in which local variables don't behave/update as expected. Both instances seem to relate to the use of items environments.

**App version**
v0.15.2 (EFM)

**Debug sheets**
[efm_chapters](https://docs.google.com/spreadsheets/d/1cJuP4B8mQ5kGzmOaOkGMkDXO201Tb5yiMvABPpnnV_w/edit#gid=1519364834
)

**To Reproduce**
Set deployment to `plh_global`, sync content and run the app and go to the template [efm_chapters](http://localhost:4200/template/efm_chapters).
1. Out of the 3 tick boxes tick only **Introductions**. Click the button **Chapter 1 (v1)** followed by **Section 1**. When hitting the back arrow in the top left corner of the screen the **Section 1** button has disappeared. It reappears upon refresh. Note that when following the same steps but using the button **Chapter 1 (v2)** instead of **Chapter 1 (v1)**, this issue does not occur. The difference between the two templates that [(v1)](https://docs.google.com/spreadsheets/d/1cJuP4B8mQ5kGzmOaOkGMkDXO201Tb5yiMvABPpnnV_w/edit#gid=1281771627) and [(v2)](https://docs.google.com/spreadsheets/d/1cJuP4B8mQ5kGzmOaOkGMkDXO201Tb5yiMvABPpnnV_w/edit#gid=995359861) of the button refer to is minimal, only the input `text` in cell `A5`.

https://user-images.githubusercontent.com/74557272/166445406-2f7e2bcd-896d-497f-a14d-85c37e3cfaff.mp4

2. Tick all 3 tick boxes. When entering the final activity (Activity 25) through a next button, it does not display correctly: there is a next button that should not be there, and this button refers to Activity 1. This is corrected upon refresh. Note that this bug does not occur when the final activity is entered directly by clicking **Chapter 1 (v1)** followed by **Section 9**. 

https://user-images.githubusercontent.com/74557272/166445807-0893b1c0-3d43-4432-9de8-ccea5d0b2be4.mp4

**Comment by chrismclarke** [comment]
I think that minimal difference might be key, as it seems to be related to the processing and reprocessing of local variables - I think possibly setting as text forces it to always use the initial value, leaving blank (i.e. set_local) will retain previous value set when reprocessing. For now, if working as intended I'd probably recommend keeping the text there and just using a hidden column to hide or style column to set `display:none`
