### ISSUE TITLE
[BUG] HTTPs cert does not renew unless server manually restarted

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1385]
Manual check of endpoint (https://apps-server.idems.international/api/) shows https certificate does not auto-renew. Work required: 

- [ ] HTTPs cert does not renew unless server manually restarted (so we should either add an auto-restart monthly or find a code workaround)
- [ ] No monitoring notification to warn us of expiry (there should be one, but likely goes to an idems email that I don't have access to)

_Originally posted by @chrismclarke in https://github.com/IDEMSInternational/parenting-app-ui/issues/1381#issuecomment-1131419059_

**Comment by EsmeeIDEMS** [comment]
I've checked in with @dannyparsons to see which email address could have received this notification, but he has not seen any notification email come in any of the general IDEMS email addresses. Is there a way to find out which address this is?

**Comment by chrismclarke** [comment]
I just had a quick look, the https is handled using [certbot ](https://certbot.eff.org/) on the server which registers certificates through the free [letsencrypt ](https://letsencrypt.org/getting-started/) service. Running the command `certbot show_account` outputs
```sh
  Account URL: https://acme-v02.api.letsencrypt.org/acme/acct/130143689
  Email contact: apps@idems.international
```
@dannyparsons - could you double check that email and see if anything came through to spam or similar? Note, the account url doesn't actually work to view (used more on the certbot backend)

**Comment by dannyparsons** [comment]
I've checked and I am receiving emails sent to `apps@idems.international` but the only ones received are from Google Play. I don't seem to have anything in spam either.

**Comment by chrismclarke** [comment]
ok, thanks for letting checking. That's very strange indeed as I have other sites that use the same system and do send automated emails to let you know certificates are going to expire soon. As part of any fix hopefully we can also apply whatever updates are available to certbot and maybe that will fix the emails.
