### ISSUE TITLE
Chat - Dynamic speech bubbles for stories

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#150]
It's clear that at some point we will need to put speech bubbles in story content with dynamic sizing (or possibly just scrollable?), with some reference to image background and speech bubble placement.

**Comment by chrismclarke** [comment]
Pushing back to 0.7.0

**Comment by michaelclapham** [comment]
Closing as illustrated stories no longer using speech bubbles to show which character is speaking
