### ISSUE TITLE
[FEATURE] Improve theme-relative asset swapping

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#1526]
**Details**
- [x] #1798
  - We want translation-specific assets and theme-specific assets to be as independent as possible
  - Currently, if a translated version of an asset exists, this will be used regardless of theme-specific versions
    - This is fine for our current use case, as we only have _images_ for the second ("professional") theme, which do not have translated versions – all of the assets for the professional theme sit inside a "global" subfolder
    - But more work is needed to handle cases where _translated_, _theme-specific_ assets exist, i.e. to handle language-code subfolders inside the professional theme folder.
- [x]  Improve asset folder structure. EDIT: This was discussed in a meeting on 09/02/23, and it was decided that the current folder structure is adequate. We would want features such as theme and language swapping to be "opt-in" for authors, so would want to avoid making theme folders mandatory
  - Currently the `theme_professional` folder sits at the [top folder level](https://drive.google.com/drive/u/1/folders/1dp9QAQ84m8pm0IBQTSPXe1ramyynKPNn), alongside the language folders
  - <img width="150" alt="Screenshot 2022-09-30 at 14 14 15" src="https://user-images.githubusercontent.com/64838927/193277810-ac6144f7-4050-42fa-aeb8-30132b56d357.png">
  - It might make more sense to put the other folders inside a sibling folder, e.g. `theme_default` or `theme_base`. This would require some refactoring of our existing code (and changes to the gdrive folder structure for each separate app), as we currently expect to find the language folders and `global` folder at the top level.
- [ ] #1950
  - Use case: 2 themes (with different names) might want to use the same asset pack
    - In which case the assets folder could be called, for example `style_human`, and could be configured as the preferred asset style for 2 separate themes.
  - This doesn't seem like a priority right now

**Comment by chrismclarke** [comment]
Following call today, proposed folder structure should make themeVariations primary filter (with all assets in _default_ theme), and language overrides secondary. Also noted that should work from authoring without any need for nested folders (only adding theme and language nesting as required)

```
"plh_audio/relax/relax_1.mp3": {
    "themeVariations": {
      "default": {
        "size_kb": 492.2,
        "md5Checksum": "0d23366a438bc1a5faf3d445e389a39a",
        "translations": {
          "tz_sw": {
            "size_kb": 596.3,
            "md5Checksum": "4917b991b1da9d8dfb62b4cbea086b9a"
          },
          "za_af": {
            "size_kb": 425.5,
            "md5Checksum": "f67195b5b8b16e13c27bea30e3daa3bf"
          }
        }
      },
      "professional": {
        "size_kb": 492.2,
        "md5Checksum": "0d23366a438bc1a5faf3d445e389a39a",
        "translations": {
          "tz_sw": {
            "size_kb": 596.3,
            "md5Checksum": "4917b991b1da9d8dfb62b4cbea086b9a"
          }
        }
      }
    }
  },
```

**Comment by chrismclarke** [comment]
Just to check @jfmcquade - Is this something you are planning on or something you would like me to?

**Comment by jfmcquade** [comment]
@chrismclarke I was planning on looking at this, it would give me a chance to look into the app sync scripts that you've just refactored. I should get a chance to do so next week. But it also might be more time-efficient for you to do it as you've just been working on the code, so feel free to. Just let me know if you make a start and I won't.

**Comment by chrismclarke** [comment]
Thanks @jfmcquade - I think unlikely that I'll have time to prioritise it anytime soon so I'd say might be good to look at as you investigate more into the assets system, and just let me know if you have any issues/questions. Always good to get a second set of eyes looking at the code/tests

**Comment by esmeetewinkel** [comment]
Closing as outstanding work is tracked in separate issue  #1950
