### ISSUE TITLE
[FEATURE] Android/Capacitor Core Updates

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1553]
**What?**
Capacitor and android core deps require updating

**Why?**
Periodically android requires updates to platforms targetted or security patches to packages used. Our android code is coupled tightly with capacitorjs, so it makes sense to update both at the same time (capacitor v3->v4 and various android file changes)

E.g. Issues raised when deploying app (first 3 should be addressed with updates)
![image](https://user-images.githubusercontent.com/10515065/195201844-62c1fe14-f4f5-4a9e-a20f-a053b1741c4a.png)

**How?**
Follow instructions at: https://capacitorjs.com/docs/updating/4-0 to upgrade capacitor v3 -> v4 and core android updates
Check working as expected on android

Can also compare against a clean capacitor app to see if there's any legacy android code floating around

**Other details**
Can use the appetize emulator to test. Also important to ensure internal testing done on device before wider deployment.
It would probably also be a good time to update gradle settings as prompted from android studio (v4.x -> v7.x)

The most important things to test for will be app launch and native integrations (e.g. push notifications, splash screen, firebase analytics/performance/crashlytics)

**Comment by EsmeeIDEMS** [comment]
C[hris's comment](https://idems-international.slack.com/archives/C02AL66MW6T/p1665519715308459?thread_ts=1665509864.575699&cid=C02AL66MW6T) on this on SLACK: 

> Of the 4 it looks to me like
>1) Another policy update required in the play console itself like done previously
>2) More of a core android issue, we rely on capacitor to populate most android code so likely they will address in an update and we should look into some capacitor core updates in the future
>3) This is pretty common and a one-liner fix from android studio (or capacitor updates). Basically every 6-12 months you need to update which android version your main target is during build. There isn't many huge side-effects of this beyond downloading new files when developing locally in android studio. But at some point it probably would be worth testing the app against android 12/13 for reference (usually android is good at retaining backwards compatibility although I think recently there were some changes to how splashscreens are handled so could be worth review)
>4) This is the one warning I always expect - to my knowledge I'm not aware of how to generate these deobfuscation files, however I feel like its not very important as our core code isn't really android code but instead javascript code that runs in the android webview (so the only obfuscated code will be the minimal capacitorjs code that initialises the app and handles native features)

**Comment by chrismclarke** [comment]
Just to check-in on this, when you look at the warnings do any of them have deadlines for compliance? might be worth prioritising if we're getting close to any of them

**Comment by EsmeeIDEMS** [comment]
The third warning has become urgent, as it now prevents us from doing a release. 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/74557272/205485898-5297ef3a-b01f-46dc-9309-6be2afc6dd38.png">

https://github.com/IDEMSInternational/parenting-app-ui/actions/runs/3612754518
