### ISSUE TITLE
[BUG] Components on some pages are off-centre

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1559]
**Describe the bug**
The components on some pages are not centred. The graphic designer thinks that this was introduced recently (last month or so), I'm not sure since I hadn't noticed the issue in the first place. 

I think it might have to do with template nesting.

**App version**
v0.16.5

**Screenshots and videos**
Not centred: 
![index](https://user-images.githubusercontent.com/74557272/195355282-7252ec1f-d456-4250-852f-0a76818f29ee.jpg)

Centred: 
![index](https://user-images.githubusercontent.com/74557272/195355387-050b7d0c-f063-4db0-b94e-3cdb0b7adc10.jpg)

**Comment by jfmcquade** [comment]
@EsmeeIDEMS I think this is fixed by #1715 and can be closed?

**Comment by EsmeeIDEMS** [comment]
> @EsmeeIDEMS I think this is fixed by #1715 and can be closed?

Yes, thanks!
