### ISSUE TITLE
[BUG] Notifications require refresh to display correctly

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1640]
**Describe the bug**
Notifications require a refresh before they are scheduled correctly. The problem seems to be that when the `activation_condition_list`, `deactivation_condition_list` and `schedule.day_of_week` column entries depend on fields, it takes a re-render for these computations to be done correctly. I was wondering if maybe these initialisation actions were not done in the right order.

**App version**
v0.16.7 

**To Reproduce**
Reset app, select either workshop or modular skin, open notifications overview page, re-render to see a lot of them disappear and the schedule change of others. 

**Template Name**
[nf_schedule_in_week_messages
](https://docs.google.com/spreadsheets/d/1JXb0lzz8Hztl6K4_3zaUpYrpq9XJjTO7YRPAsx03F-4/edit#gid=513586624)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/74557272/200337277-e0130097-8205-4d19-a834-58176e403403.png">

**Screenshots and videos**
For workshop skin (so `@fields.iwm_as_notifications == TRUE`): 

- Immediately after app reset
<img width="181" alt="image" src="https://user-images.githubusercontent.com/74557272/200337793-eb5b95f6-a925-438f-b4da-aa4901822acd.png">

- After refreshing the browser tab
<img width="177" alt="image" src="https://user-images.githubusercontent.com/74557272/200337985-ecbcdb60-362e-4641-9f69-00739742c754.png">

**Comment by jfmcquade** [comment]
Adding my diagnosis of the issue that was previously on Slack:

In the example sheet attached to the issue, the notification schedule rows depend on fields, the values of which aren't set at the point of the campaign service being initialised (wherein the notifications are scheduled). The values are set by the template-process-service, which is initialised after the campaign-service in app.component.ts.

Specifically, the field workshop_number is set in the template timing_calculations, which is one of the "startup templates" (i.e. it has a value for process_on_start, and is therefore processed by the template-process-service on initialisation). When the campaign service is initialised and these notifications are scheduled, the field workshop_number is undefined and so the deactivation conditions that depend on its value being equal to 1 do not pass, and the notifications are not deactivated.

**Comment by chrismclarke** [comment]
Thanks for diving so deep into this @jfmcquade. So I'm guessing really the proper fix for this is the same as that mentioned in the data_groups RFC for campaigns to actively monitor the fields they refer to and recalculate on change. As that's unlikely to be implemented in the short term, I'm guessing we need some sort of workaround to reprocess campaigns after the startup templates? Or move the logic for processing startup templates into another core service which we can try to initialise before campaigns?

Neither solution sounds super pretty, but I'd say I'm happy with a somewhat hacky fix given the nature of these cyclic deps and longer term solution to follow
