### ISSUE TITLE
[Crashlytics] Uncaught (in promise): Error: 7: Error: 7: at Object.cap.fromNative

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1653]
**Details**
- 35 non-fatal events affecting 25 users
- some users have lots of free disk space so that doesn't seem to be the issue

[See on Firebase
](https://console.firebase.google.com/u/0/project/plh-teens-app1/crashlytics/app/android:international.idems.plh_teens_tz/issues/61de7e9742aeef8ed4b30d3b5baa709d?time=last-thirty-days&sessionEventKey=636B8B4502C1000122C6CC32E7263EC9_1742418482340084612)

<img width="773" alt="image" src="https://user-images.githubusercontent.com/74557272/200876929-3fc68bdf-8698-4c39-b01f-9ca16487ceea.png">

```
Non-fatal Exception: com.getcapacitor.community.firebasecrashlytics.JavaScriptException
Uncaught (in promise): Error: 7: Error: 7: at Object.cap.fromNative (http://localhost/:413:32) at <anonymous>:1:18
.Object.cap.fromNative (Unknown Source:413)
.(anonymous function) ((unknown file):1)
.z (polyfills.c906600eb8317419.js:1)
.(anonymous function) (polyfills.c906600eb8317419.js:1)
.at (main.d1af5c4fe9575d20.js:1)
.T.invoke (polyfills.c906600eb8317419.js:1)
.Object.onInvoke (main.d1af5c4fe9575d20.js:1)
.T.invoke (polyfills.c906600eb8317419.js:1)
.T.run (polyfills.c906600eb8317419.js:1)
.(anonymous function) (polyfills.c906600eb8317419.js:1)
.T.invokeTask (polyfills.c906600eb8317419.js:1)
.Object.onInvokeTask (main.d1af5c4fe9575d20.js:1)
```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/74557272/200877379-a93bb8ed-4f09-43f4-a756-d28209ace43f.png">

**Comment by chrismclarke** [comment]
It's unclear exactly where this is originating from so will not be able to further diagnose until we have better tooling in place

**Comment by esmeetewinkel** [comment]
@jfmcquade Do you think we can close this?

**Comment by jfmcquade** [comment]
> @jfmcquade Do you think we can close this?

Yes, I think so. The original logs didn't contain enough information to diagnose the source of the error, and I can't find an equivalent bug in glitchtip. So I think we can safely assume that either the bug has been fixed, or it is manifesting as a different bug that is logged to glitchtip and can be dealt with independently.
