### ISSUE TITLE
[FEATURE] In-app pop-up when a new release is available

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1678]
**What?**
In-app pop-up when a new release is available. 

**Why?**
Facilitators are struggling to communicate to users how to update their app through the Play Store. This feature would make it a lot easier.

**Comment by chrismclarke** [comment]
Should be possible through use of plugin:
https://github.com/capawesome-team/capacitor-app-update

Example of how android handles this natively:
https://developer.android.com/guide/playcore/in-app-updates

Alternatively we could display our own screen/popup/template if prefereable
