### ISSUE TITLE
[FEATURE] Dynamic data lists 

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1712]
**What?**
Dynamic data lists 

**Background**
Datalists are the main means of rendering looped content in the app, such as workshop items, campaign rows, tasks etc. They can be dynamically generated prior to compiling via data_pipes, however, during runtime they are static.

We often want to track interactions related to specific datalist items, such as when a task in a datalist is marked as completed. Furthermore, we often want to link sets of lists together, to track things such as whether multiple tasks have been completed within multiple workshops

**How?**
[IDEMS App - Data Groups RFC](https://docs.google.com/document/d/1saH0_PzkbLTwO0fea4lPtuLnyYga30W_uhiO9CEcEgg/edit#heading=h.y034rw1a1svj)

**Comment by chrismclarke** [comment]
@esmeetewinkel - I think the main work on this has now been integrated, so recommend either closing this issue and adding any specific follow-ups separately, or renaming
