### ISSUE TITLE
Dynamic components inside items environment

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#1720]
**Details**
I'm trying to author combo boxes and text boxes inside an items environment (that loops over a list of numbers 1,2,3,...,n). I would like the component to show the field value of the corresponding field by default, however, that field name is dependent on the id of the item. I don't know how to author this in a spreadsheet cell without brackets. 

**Debug sheet**
<img width="929" alt="image" src="https://user-images.githubusercontent.com/74557272/212734925-488ca563-21ca-4b31-87f4-fbd010f2c3db.png">
[debug_teen_ages](https://docs.google.com/spreadsheets/d/1vm9aDgmBaJBQfl6CgAje8Ys02qicW2M8v96JaMJ5-f8/edit#gid=1422144003)

**Screenshots and videos**
<img width="949" alt="image" src="https://user-images.githubusercontent.com/74557272/212734828-af4bb1ad-d681-4db0-b3e9-d3b07e96374a.png">

**Comment by chrismclarke** [comment]
Summary of slack response:

- Create a separate data_list to use for household teen info (including numbers and columns for data/fields)
- Refer to row own value via `this` in action list

**E.g. list**
![image](https://user-images.githubusercontent.com/10515065/212744052-1227515c-6664-4205-bb2b-e43947f93188.png)

**E.g. row**
![image](https://user-images.githubusercontent.com/10515065/212744133-36740762-ebc4-473c-b87e-3f46aab7a7a3.png)

**Comment by chrismclarke** [comment]
Would be good to documen (using actions)t:

Use `this.value` when referring to `changed` action to pick the updated change value. Referring to @local will always be the value before the change

**Comment by EsmeeIDEMS** [comment]
@chrismclarke I've tried your solution, however, I'm now stuck at another point: For some reason the `text_box` corresponding to the last item of my items-loop is tied to the others - whenever another `text_box` is updated the last one updates as well...

[screen-capture (20).webm](https://user-images.githubusercontent.com/74557272/213541695-7d5e0a62-5fe5-4db6-96db-ab32fefdc0b8.webm)

<img width="660" alt="image" src="https://user-images.githubusercontent.com/74557272/213543301-40a32084-07b3-4c81-873d-47795d85cd94.png">
I've pasted my current version of this sheet (demographics_teen_age in the video) into 
[debug_teen_age](https://docs.google.com/spreadsheets/d/1vm9aDgmBaJBQfl6CgAje8Ys02qicW2M8v96JaMJ5-f8/edit#gid=1422144003)

**Comment by chrismclarke** [comment]
Interesting, I've found a bug in the code where referring to `this.value` doesn't work from inside a display group. I'll try fix that and see if it helps to resolve the issue you're seeing

**Comment by chrismclarke** [comment]
Thanks @EsmeeIDEMS , on first look this feels like a potential issue with the parser not preserving the correct values on deeply nested data (wouldn't be the first time) - the authoring looks fine to me so I'll see if I can figure it out

**Comment by chrismclarke** [comment]
I've tried taking a deeper look, and indeed I can see there is an issue at the parser level where it is losing reference to the nested items when setting the local value (works fine for setting fields, so the values are correct after a refresh). 

I still think this might be a good candidate for the new `data_items` syntax now that it has been merged, however I'll still try open a PR to fix the current behaviour

**Comment by chrismclarke** [comment]
@EsmeeIDEMS - should be fixed in #1743
