### ISSUE TITLE
[BUG] Checkbox becomes rectangle on narrow screen

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1739]
**Describe the bug**
Checkbox should always be a square. Currently, the checkbox adapts to narrow widths by becoming a rectangle. This looks bad, and moreover the checkbox is no longer recognisable as such.

**App version**
v0.16.9

**Template Name**
[accept_terms](https://docs.google.com/spreadsheets/d/1MJzzdTYDZg0VkS5zxrXY4lKV5Oi954pw1sIVJUOOzWM/edit#gid=1884781962) which is part of the first app launch sequence:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/74557272/213761219-65636248-b030-487f-93ac-2a122528ce60.png">

**Debug Template**
[comp_simple_checkbox](https://docs.google.com/spreadsheets/d/19t6lEBkVF0LV2dMD1yL6nbuUIFiiYNa0xLA1QQAyyxU/edit#gid=569531329)

[screen-capture (21).webm](https://user-images.githubusercontent.com/74557272/213762025-793603af-6141-4194-9f08-ba5fe030bd9b.webm)

**Comment by EsmeeIDEMS** [comment]
There's a workaround: rather than using the `label_text` parameter on the checkbox, you can just use the checkbox without parameters and put it in a display group together with a regular `text` component, in which you specify the label text. 

So fixing this is very low priority.
