### ISSUE TITLE
Lists with additional content need to be distinguished from lists without additional content

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#175]
In https://plh-demo1.idems.international/toolbox/topic/ONE_ON_ONE_TIME/1on1_Ideas we have list with accordion style arrows. Could they be changed to dots instead?

Without text:
![image](https://user-images.githubusercontent.com/46322225/101051701-b2177d00-357d-11eb-8226-9acc291bbc39.png)

List with text where accordion is correct:
![image](https://user-images.githubusercontent.com/46322225/101051901-ea1ec000-357d-11eb-8c95-c32ad49e9b5f.png)

**Comment by smborio** [comment]
Also, the triangles are different for some reason. Maybe this should be a new issue?

**Comment by michaelclapham** [comment]
Closing as the toolbox is no longer being used
