### ISSUE TITLE
[BUG] Fields not populating correctly when using items dynamically

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1765]
**Describe the bug**
I've not been careful enough doing the functional test to PR #1743, there seems to be a remaining bug: Although this PR visually fixes the problem noted in issue #1720, the fields associated to the various text boxes are not always set correctly. 

See screen video for the behaviour. My current working hypothesis is that it happens when an input box is revealed for the first time AND it is the last input box being displayed.

**App version**
v0.16.11

**Debug Template**
[debug_teen_ages](https://docs.google.com/spreadsheets/d/1vm9aDgmBaJBQfl6CgAje8Ys02qicW2M8v96JaMJ5-f8/edit#gid=1422144003)

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/215847136-79f3e00d-d126-45d0-a2a6-36d5a327dd7f.png)

[screen-capture (24).webm](https://user-images.githubusercontent.com/74557272/215846763-e2b2001c-2e09-48b5-9cdb-57edf5babd2b.webm)

**Additional comments**
At this point I'd be happy with any work-around to this issue, including using `data_items` instead of `items`. However, being able to extract this data from the Postgres database is essential (the only reason this question is asked is for data collection purposes) - and I don't think we have this set up for values stored in dynamic data lists rather than in fields.

**Comment by esmeetewinkel** [comment]
@jfmcquade looked into this and commented (private thread on SLACK): I would say it's a direct knock-on from [PR 1743](https://github.com/IDEMSInternational/parenting-app-ui/pull/1743) – the `_nested_name` is now being evaluated, but it is not being evaluated correctly (i.e. `items.dg_sect_undefined1`).

**Comment by chrismclarke** [comment]
@esmeetewinkel - do you definitely have the latest branch checked out? When testing locally on master branch I can't recreate the behaviour (unless I'm missing something)

[Untitled_ Jan 31, 2023 12_10 PM.webm](https://user-images.githubusercontent.com/10515065/215871675-13cbf7f8-21fe-4445-8a81-05b9349526f8.webm)

**Comment by esmeetewinkel** [comment]
> My current working hypothesis is that it happens when an input box is revealed for the first time AND it is the last input box being displayed.

I probably did not make myself very clear here, should have instructions on how to reproduce. It only happens on the **last** text box that is being displayed, and only when it is being displayed for the **first** time. To reproduce: 

1. Run the app locally on the `master branch` with deployment set to `plh_global`
2. Clear local storage of fields
3. Navigate to http://localhost:4200/template/debug_teen_ages
4. Select **3* in the number of teens in your household
5. Select the **third** text box 
6. Type something
7. Click outside of the text box to save (so that the "changed" action happens)
8. Observe the error in the console 

On my end the error is a bit erratic, earlier today these steps 1-8 were what was happening but now actually 6 and 7 are skipped (i.e. immediately after 5 I'm seeing errors in the console).

<img width="462" alt="image" src="https://user-images.githubusercontent.com/74557272/215887638-f0cdf29b-a777-4a38-af87-7823980f3c60.png">
