### ISSUE TITLE
Open Welcome Flow is not opening Open Welcome Flow

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#177]
![image](https://user-images.githubusercontent.com/46322225/101053169-5d750180-357f-11eb-897f-8d3c306d87f4.png)

https://plh-demo1.idems.international/settings

**Comment by michaelclapham** [comment]
This should be fixed. @smborio Please let me know if Welcome_Intro is the correct welcome flow to launch.

**Comment by chrismclarke** [comment]
Can possibly just remove as we have the main list, or just fix
