### ISSUE TITLE
[FEATURE] Notification dependent on completion of highlighted module

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1799]
**What?**
I would like to send a notification related to the highlighted module and its completion level. Specifically, the notification will depend on whether the module has been started (at least one task completed) or not (zero tasks completed). 

**How?**
I started authoring these in this [sheet](https://docs.google.com/spreadsheets/d/1RztJVUiuQZhXLN5lI0BUWcDqL9sBAz8_MbQwbWvfNb4/edit#gid=234155673).

**Comment by jfmcquade** [comment]
PR #1802 adds a workaround that should cover this use case
