### ISSUE TITLE
[BUG] Infinitely many errors when entering the app through a notification

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1805]
**Describe the bug**
When entering the app through a notification the console shows an unlimited number of errors (quickly climbing up to >1000). These seem to have to do with a missing title. This issue happens both for notifications that have an explicitly defined "title" in the sheet and those that don't (i.e. are using the default title "New message from PLH"). 

```
ERROR TypeError: Cannot read properties of undefined (reading 'title')
```

<img width="339" alt="image" src="https://user-images.githubusercontent.com/74557272/220417055-84878c56-9f48-4e54-8795-06c658afe4c0.png">

**App version**
v0.16.11

**To Reproduce**
- navigate to https://plh-global.web.app/notifications
- send yourself a notification
- click the notification to enter the app
- observe the errors in the console. 

**Screenshots and videos**

[screen-capture (37).webm](https://user-images.githubusercontent.com/74557272/220416485-ce1344c5-84c7-4b3d-9b02-936c0a629465.webm)

**Additional comments**
I don't know whether this behaviour has any knock-ons of breaking anything in the app that a user would notice. If it doesn't then this issue is low priority.

**Comment by chrismclarke** [comment]
Thanks @esmeetewinkel , taking a quick look on glitchtip I can see we are also tracking this error (and the stack traces working)

https://app.glitchtip.com/idems/issues/1711211
![image](https://user-images.githubusercontent.com/10515065/221016454-11c272fd-2c15-45ab-bee8-072ed21c3bed.png)

I might suggest @jfmcquade take a first look at this one if he has the time.

It might also be worth adding to a future call checking through any of the other issues being tracked in glitchtip for triage
