### ISSUE TITLE
BUG - Self Care > Module > Reward > the "Next" button not working

### ISSUE THREAD

**Issue by lenkada** [IDEMSInternational/parenting-app-ui#1860]
BUG - Self Care > Module > Reward > (third page in) > the "Next" button not working.

App Version v0.16.15

<img width="221" alt="image" src="https://user-images.githubusercontent.com/113142748/225990949-4496cbdd-166e-4a13-bf1b-6f470218cc6d.png">

@jfmcquade / @chrismclarke (tagging Chris C because of the time difference and wondering if able to address).

**Comment by chrismclarke** [comment]
Seems to be an authoring issue, proposed fix in google sheet [comment](https://docs.google.com/spreadsheets/d/17lfsNZGb_3KYiMudc5SoxEj16uWxABrVKKW-4BAiLoA/edit?disco=AAAAsQPTBCM)
