### ISSUE TITLE
[CHORE] Update nestJS version to v9

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#1863]
**Details**
Dependabot opened #1833 to update [@nestjs/core](https://github.com/nestjs/nest) from 7.6.15 to 9.0.5. But it's not clear what breaking changes this may introduce. Therefore, the update should be done manually.

Migration guide Nest 7 -> 8
https://8-0-0--docs-nestjs.netlify.app/migration-guide
Migration guide latest (currently Nest 8 -> 9)
https://docs.nestjs.com/migration-guide

**Comment by esmeetewinkel** [comment]
@jfmcquade Can this be closed? I found that on `master` in the relevant file `@nestjs/core` is `9.4.3`

**Comment by jfmcquade** [comment]
Completed as of #1893
