### ISSUE TITLE
[FEATURE] Share to WhatsApp

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1925]
**What?**
Ability to select text (essential) and files (images, pdfs - desirable) in the app and share to WhatsApp. 

**Why?**
Requirement from Facilitator App Malaysia deployment. 

**How?**
Assuming this is only needed to select known text in certain contexts (as opposed to adding the ability to select arbitrary text within the app), I think it would make sense to add the functionality to the select_text component ([demo template here](https://docs.google.com/spreadsheets/d/1MX-sy4RLy7xPkl0vHZ0lfp-kzGWyohViWjNhyGn7Vts/edit#gid=845703892), [web preview demo here](https://plh-global.web.app/template/comp_select_text)). It should be straightforward to do so using [capacitor's share API](https://github.com/ionic-team/capacitor-plugins/tree/main/share) ([docs](https://capacitorjs.com/docs/apis/share#shareoptions)). This would bring up Android's native share menu, meaning the user would manually have to choose to share via whatsapp and select the intended whatsapp group

See also #1951 about sharing files

**Comment by jfmcquade** [comment]
Assuming this is only needed to select known text in certain contexts (as opposed to adding the ability to select arbitrary text within the app), I think it would make sense to add the functionality to the `select_text` component ([demo template here](https://docs.google.com/spreadsheets/d/1MX-sy4RLy7xPkl0vHZ0lfp-kzGWyohViWjNhyGn7Vts/edit#gid=845703892), [web preview demo here](https://plh-global.web.app/template/comp_select_text)). It should be straightforward to do so using [capacitor's share API](https://github.com/ionic-team/capacitor-plugins/tree/main/share). This would bring up Android's native share menu, meaning the user would manually have to choose to share via whatsapp and select the intended whatsapp group
