### ISSUE TITLE
[Glitchtip] – '[data_list] "_ind_task_gs" not found'

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#1962]
**Glitchtip Link**
Main issue (`plh_tz`): https://app.glitchtip.com/idems/issues/1984141

`pfr` issues, likely related:
https://app.glitchtip.com/idems/issues/2092756
https://app.glitchtip.com/idems/issues/2092754
https://app.glitchtip.com/idems/issues/2092755
https://app.glitchtip.com/idems/issues/2092753
https://app.glitchtip.com/idems/issues/2092782
https://app.glitchtip.com/idems/issues/2092752
https://app.glitchtip.com/idems/issues/2092761
https://app.glitchtip.com/idems/issues/2092749
https://app.glitchtip.com/idems/issues/2092748

**Report txt**
```js
Error:[data_list] "_ind_task_gs" not found
 at w.<anonymous> (/main.8bdfdf9faf11d6d6.js:1:1298823)
 at Generator.next (<anonymous>)
 at ? (/main.8bdfdf9faf11d6d6.js:1:2658915)
 at new M (/polyfills.e91c1101d08ae204.js:1:46616)
...
```

**Diagnosis (if known)**
Looking at the breadcrumbs, the error is always preceded by the log "[HIGHLIGHTED TASK GROUP] - No highlighted task group is set", which occurs when the tasks have all been completed (see #1960 for a related fix). The issue can be replicated locally by completing all the tasks. 
It appears that when all task groups are completed, the template variables service looks for a data_list called `_ind_task_gs`, which does not exist. 

**Suggested fix (if known)**
It may be that this can be fixed from an authoring level, but further investigation is needed. Look in authoring for where the string `@data._ind_task_gs` might be compiled (e.g. [task_card](https://docs.google.com/spreadsheets/d/1WGXQpDIzsS-FbDX_aLXJ4geT03Uqjdc4Fm4m2C2W2fY/edit#gid=1983421448)) – or it may be easier to look at the data list names from the pfr issues.

**Comment by esmeetewinkel** [comment]
I think this relates to the issue flagged by Elena: 

<img width="464" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/25dbdfc4-7485-4c35-8a78-b07607191ff6">

**Comment by esmeetewinkel** [comment]
Resolved by commit https://github.com/IDEMSInternational/parenting-app-ui/commit/1839e9aab6e2eb3b75266c3bbc476d586f1167e0
