### ISSUE TITLE
[BUG] toUpperCase() method in @calc doesn't work

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#1974]
**Describe the bug**
I would like to be able to change a string to upper case using the `@calc` function. I cannot use a spreadsheet function for this, because then both the regular and upper-case string would need to be translated, which is exactly the situation I'd like to avoid. 

I thought I would be able to do this with `@calc`, saving the string to a local variable and then using the syntax `@calc(@local.some_string.toLowerCase())`. 

However, doing this I get a console error `TypeError: Cannot read properties of undefined (reading 'operatingSystem')`
<img width="563" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/998357c2-5a6b-465a-a23f-09a4e24cbe7b">

**App version**
v0.16.17

**Debug Template**
[example_calc_4](https://docs.google.com/spreadsheets/d/15TccctjzepSPPv9xrLp46fhYldNN0wrho1zA5voTYcg/edit#gid=1417284859) (`debug` deployment, might need to sync content first)
<img width="288" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/9bfc85bf-75a6-4f3c-8720-a2217599181e">

**Comment by esmeetewinkel** [comment]
Priority: medium if quick, low if it takes a lot of time

**Comment by jfmcquade** [comment]
This appears to be working for me, at least when I use the author the `@calc` value in its own local variable, as you have done for `some_string_lc`.

Updated [template](https://docs.google.com/spreadsheets/d/15TccctjzepSPPv9xrLp46fhYldNN0wrho1zA5voTYcg/edit#gid=1417284859):
<img width="600" alt="Screenshot 2023-07-05 at 12 02 39" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/6b4ce599-61b1-4fbd-94be-1a7856f5931d">

Template in-app:
<img width="300" alt="Screenshot 2023-07-05 at 12 03 30" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/8c575b30-8870-4adf-9d1d-5c3bc7c4a278">

Interestingly, I don't get the error that you do when my template is in the state that it's in in your screenshot. I get the value displaying as "null", but no error in the console:
<img width="900" alt="Screenshot 2023-07-05 at 11 55 55" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/d880587f-6839-4396-8848-a8bc2e13520e">
I'm not sure what's causing that error – the `operatingSystem` value mentioned in the error isn't coming from our code directly, so is seemingly a core Javascript error, perhaps some difference in the way different browsers treat Javascript? Difficult to debug as I can't recreate the error
