### ISSUE TITLE
[BUG] Generator does not ignore @default row

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2018]
**Describe the bug**
When looping a generator sheet over a data list with an `@default` row, the `@default` row also results in a generated flow. Instead, this row should be ignored by the generator as it does not represent an actual row of data.

<img width="304" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/d8e9e650-ef66-48a4-b525-176639d768d6">

**App version**
v0.16.17

**Comment by esmeetewinkel** [comment]
My bad, this is not because of the default row but because I had a row without an id (which sat somewhere low down in the spreadsheet so I had missed it)

**Comment by esmeetewinkel** [comment]
> Is this something we need to add an extra catch/warning for somewhere? Can't remember if we ended up agreeing all data lists need an id column or not (I think only technically only really needed for lists working with data pipes)

We do also need the id column to use the syntax `@data.sheet.row_id.column`. I actually quite like insisting on an id column, because it forces authors to think a little bit more abstractly about their content (to determine the identifying factor of a row that is unique within the sheet). 

A warning for a row without id would be helpful! And also when the id column is missing (I've found that even when `id` is written as `ID` the sheet breaks, but there is no clear warning).

**Comment by chrismclarke** [comment]
@esmeetewinkel 
Issue created https://github.com/IDEMSInternational/parenting-app-ui/issues/2039

I've tried to write it up in a way that someone else can take it on if desired, otherwise would assume low priority on my own TODO list
