### ISSUE TITLE
Triangles in speech bubbles seem different

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#205]
![image](https://user-images.githubusercontent.com/46322225/101650100-7d9b3980-3a33-11eb-8c4e-c9ab29bb1dbd.png)

As you can see in the picture below, there are inconsistencies with the left border of the boxes which makes the triangles look different.

mod_welcome_self-care_package -> chose have a relaxed bath to get to this screenshot but it is common elsewhere

**Comment by michaelclapham** [comment]
Closed as chat no longer being used
