### ISSUE TITLE
Line breaks are not being recognised

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#206]
![image](https://user-images.githubusercontent.com/46322225/101650100-7d9b3980-3a33-11eb-8c4e-c9ab29bb1dbd.png)

In the picture above there is a list in a message. In the excel this is a single cell with multiple lines which should be interpreted as line breaks but this doesn't seem to be the case.

![image](https://user-images.githubusercontent.com/46322225/101651197-b4258400-3a34-11eb-9843-fc2d0c834f13.png)

flow: calm_5

Spreadsheet: https://docs.google.com/spreadsheets/d/15bIQeD_WHDL21wg_qRVAS4NUyBkYsKmVDBDL6WxTR8w/edit?usp=sharing (sheet calm_5)

**Comment by chrismclarke** [comment]
![image](https://user-images.githubusercontent.com/10515065/101994879-cdb80d00-3c7a-11eb-9b88-610a698fb9a8.png)
Fixed
