### ISSUE TITLE
[FEATURE] Download PDF to device

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2064]
**What?**
There's been a request by the FacilitatorApp to have download of PDF files to the device. 

**Why?**
The reasoning is that 
1. People didn't find the in-app PDF viewer easy to use because it doesn't take up the full screen, and they were using devices with relatively small screens. They prefer using another PDF viewer on their device. 
2. People want to save the PDF to their device to be able to access it easily afterwards.

I do feel that these particular issues could also be resolved by making our PDF viewer and use thereof better...

**How?**
I'm not sure if this should be a feature of the PDF viewer (PR https://github.com/IDEMSInternational/parenting-app-ui/pull/1913) or that this is more related to sharing files [#1951](https://github.com/IDEMSInternational/parenting-app-ui/issues/1951).

**Comment by esmeetewinkel** [comment]
This is brought forward as a priority for FacilitatorApp https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/42 

This issue also talks about reducing the padding around the PDF viewer component. To me it would make more sense to add a full screen mode to the PDF viewer rather than removing the padding.

**Comment by jfmcquade** [comment]
The quickest route to this feature is likely to be using the share menu (as in #1941), and adding a custom button to the pdf component.

Eventually the functionality to download files should be available for arbitrary asset files (using [@capacitor/filesystem](https://capacitorjs.com/docs/apis/filesystem) and the file manager service), and exposed as a template action
