### ISSUE TITLE
[BUG] Debug deployment database not created

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2098]
**Describe the bug**
Following the work done on PR #1893 (as a workaround for issue #1865) I want to create separate database tables per deployment. To test this, I updated the config of the `debug` deployment to contain 
```
config.api = {
  db_name:'debug',
}
```
but now the [debug app web preview](https://idems-debug.web.app/) no longer syncs to the server. 

**App version**
v0.16.21

**To Reproduce**
Go to https://idems-debug.web.app/template/debug_sync_id and observe that syncing doesn't work. 

**Debug Template**
[debug_sync_id
](https://docs.google.com/spreadsheets/d/18-lgxZqJ6_3DRhrxwxgutVHsMAXjOVtoBAxN5l7kaQY/edit#gid=1422144003)

**Screenshots and videos**
<img width="953" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/b3452597-0625-4d64-a424-34faedc0728a">

**Additional context**
@jfmcquade and I discussed this in [this mattermost thread](https://chat.idems.international/all/pl/g5i3jabxa3ffpgr14qooeus9oo).

**Comment by jfmcquade** [comment]
I may have found the problem, see [this PR](https://github.com/IDEMSInternational/app-debug-content/pull/37) on the debug content repo.

`config.api` contains 2 properties: `db_name` and `endpoint`, where the latter has the default value "https://apps-server.idems.international/api". The syntax you'd used to add `db_name:'debug'` was overwriting the value of the whole `config.api` object, not just the `db_name` property, so it was effectively setting `endpoint` to `undefined`. 

This isn't noticeable when running locally, since the `endpoint` is always replaced with "http://localhost:3000" in that case. But after merging that PR, we should see the database created correctly by using the template at https://idems-debug.web.app/template/debug_sync_id

**Comment by esmeetewinkel** [comment]
Thanks, great, I can see the debug database (and `app_users` table) now in pgAdmin.

<img width="957" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/eddb3f92-102c-4668-b1b2-c30234a0a9b3">

Next challenge is to make that database appear in Metabase. I [was able to add it](https://apps-server.idems.international/dashboard/admin/databases/5) using a general login, however, looking at how [Cleaned PLH data](https://apps-server.idems.international/dashboard/admin/databases/4) and [PLH DB](https://apps-server.idems.international/dashboard/admin/databases/2) are set up I'm wondering if we should create a specific login for this. Do you have admin rights on the server (or however I should call the workspace that pgAdmin4 lets me view) so that you can create this account (I think it only needs read access to the debug database)? 

N.B. [Here](https://docs.google.com/document/d/1YLxLQfr0UC0VdA-fVOVeKSnHaVySi2gQ7FCLQQozqv8/edit#heading=h.6efk3dgeegpt)'s the doc which explains how to add users in pgAdmin. I am logged in with a general login, and I don't seem to be allowed to add users
<img width="271" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/7ecae1da-3c84-4d4c-9d55-e260b8de6093">

**Comment by jfmcquade** [comment]
> Not sure why we immediately have 16 rows!?

Hmm potentially from some data for the debug site that has been saved locally (to my device?) and then just all synced at once? Not sure though

> Do you have admin rights on the server (or however I should call the workspace that pgAdmin4 lets me view) so that you can create this account (I think it only needs read access to the debug database)?
> N.B. [Here](https://docs.google.com/document/d/1YLxLQfr0UC0VdA-fVOVeKSnHaVySi2gQ7FCLQQozqv8/edit#heading=h.6efk3dgeegpt)'s the doc which explains how to add users in pgAdmin. I am logged in with a general login, and I don't seem to be allowed to add users

It looks like I also don't have permissions to create a new user
<img width="250" alt="Screenshot 2023-10-10 at 17 13 12" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/d63db9b1-6052-4277-b203-0c541ea4c383">

**Comment by esmeetewinkel** [comment]
@chrismclarke Could you advise here? (checked with Johnny and Lily first but neither could help out)

**Comment by chrismclarke** [comment]
It looks like now there's significantly more data populated - syncing from `plh_tz`, `wash`, and `plh_facilitator` apps which makes no sense as they should be populating to `plh` db instead. 

My only guess right now is perhaps the volume of data coming in is too much to process with the current mechanisms to change db target per request, or some other issue in the code (although I feel like we did do functional testing at the time...)

I'll have to try investigate further this week, for now I'll send a couple requests to force db defaults back to plh db
