### ISSUE TITLE
[FEATURE] Android assets workflows for separate content repos

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2109]
**What?**
Revise whether [Android asset generation workflows](https://github.com/IDEMSInternational/parenting-app-ui/pull/1413) still make sense and work for deployments whose content sits in a stand-alone repo.

**Comment by jfmcquade** [comment]
Additionally, the package we use to generate the Android assets has been deprecated in favour of [capacitor-assets](https://github.com/ionic-team/capacitor-assets) (which is CLI only so will need a new adapter)

**Comment by esmeetewinkel** [comment]
Work-around by putting it into the android build workflow

**Comment by esmeetewinkel** [comment]
> Additionally, the package we use to generate the Android assets has been deprecated in favour of [capacitor-assets](https://github.com/ionic-team/capacitor-assets) (which is CLI only so will need a new adapter)

https://github.com/IDEMSInternational/parenting-app-ui/issues/2072

**Comment by esmeetewinkel** [comment]
@jfmcquade to mention in [documentation](https://idemsinternational.github.io/parenting-app-ui/developers/android-assets/) that this is part of github action, and then close this issue

**Comment by chrismclarke** [comment]
Is this something still required? Not sure if it might be closed alongside work in #2252 @jfmcquade ?
