### ISSUE TITLE
[CI] Code version releases

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#2112]
**Details**
It was suggested that we move to a regular release cycle, where the app version is incremented to reflect changes to the code at regular intervals. Making use of github's [releases](https://github.com/IDEMSInternational/parenting-app-ui/releases) feature a new version should be released on an ad hoc basis, but at least once a month.

**Comment by jfmcquade** [comment]
Content branches should point to a specific tag (version number) to use a specific version of the codebase.

There should be a process (automated) for updating a content branch to point to a different version of the code, e.g. latest stable, latest beta, specific version number.

If a content branch is pointing directly to the master branch, this should be named to indicate that it is using the development build (rather than using a version number).

**Comment by jfmcquade** [comment]
## Proposed release process

1. Bump number in package.json
2. Merge to master (will update latest draft release)
3. Publish latest draft release
4. Update organisational variable `APP_CODE_BRANCH` to point to latest variable tag
  - This variable will be used to specify which code version each deployment repo will use when building the app. Can be overridden at the deployment level by adding `APP_CODE_BRANCH` to the deployment repo.

**Comment by esmeetewinkel** [comment]
@jfmcquade Can we close this issue?

**Comment by jfmcquade** [comment]
Yes I think so, although it could be worth included the steps outlined in my last comment in the documentation. I'm looking at documentation today so can include this change and close this issue on merge
