### ISSUE TITLE
[FEATURE]: Task group progress bar

### ISSUE THREAD

**Issue by lenkada** [IDEMSInternational/parenting-app-ui#2150]
**What?**
New "progress bar" navigation for a task group ("category") that contains of multiple tasks ("articles", corresponding to a single screen). N.B. In the PLH Kids use case we have three layers of task nesting: module - category - article

<img width="156" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/220de25d-a979-4a72-8eca-a0feb47c3fdb">

1. progress bar appears if a task group contains more than one task. Progress bar is 1/n filled on the first task, 2/n on the second task, and filled up entirely on the last task. 
2. "cross" appears in the top right corner and exits the current task group (taking the user back to the module landing page)
3. "next" button at the bottom of the screen takes user to next task within the task group. If at the last task of the task group, this will take the user to the first task of the following task group. (unclear whether this should be the highest priority task group or the highest priority uncompleted task group). If at the last task of the last task group of the module, should take back to module landing page.
4. "back" button appears only when a task group has multiple tasks, on all but the first task.

**Why?**
Required for PLH Kids deployment but would apply to FacilitatorApp and PLH Teens deployments in future too. 

**How?**
3. Moving from "completing one category" to the next will be using a function authored in the code to evaluate which task is next (as discussed with @jfmcquade)

**Comment by avelynhc** [comment]
Hello, can I work on this? Thanks!

**Comment by jfmcquade** [comment]
@avelynhc This is quite a specific issue that needs further discussion. If you're interested in contributing there might be some more suitable issues for getting started with the codebase. Perhaps #1804 would be a reasonable starting point?
