### ISSUE TITLE
[FEATURE] Display an image with no padding/margin

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#2151]
**What?**
An image should be able to have no margin/padding
<img width="276" alt="Screenshot 2023-11-21 at 15 18 22" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/015a41bd-060b-4617-8799-56f15582a3fb">

**Why?**
See [issue on content repo](https://github.com/IDEMSInternational/plh-kids-app-content/issues/3).

**How?**
Could probably be achieved with a new style/variation on the image component itself.

**Comment by esmeetewinkel** [comment]
This request became redundant because of updated design

![image](https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/e2b995fe-98cf-4dee-9153-3bc20a989426)
