### ISSUE TITLE
[CHORE] Provide scope of work for MTN Ayoba deployment

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/parenting-app-ui#2156]
**What?**
From a WIP contract, we must provide:
> A cost estimate, delivery timeline, and scope of work description for the delivery of a single deployment of each product within Ayoba. The deployment will include content localisation for a single country and up to two languages.

**How?**
Consult the [Ayoba developer docs](https://developer.ayoba.me/) and establish what would be required to publish a functioning app to the platform. 

Document the native SDKs we use through Capacitor (this will also be useful for #1422). Are they implemented in browser on mobile platforms? If not, what work would be required to implement them (e.g. Ayoba's native APIs)?

**Comment by esmeetewinkel** [comment]
@jfmcquade Can this be closed?
