### ISSUE TITLE
[FEATURE] Parenting for Respectability Theme colours

### ISSUE THREAD

**Issue by laetitiaCA** [IDEMSInternational/parenting-app-ui#2165]
**What?**
Update the Parenting for Respectability App theme to have  Green, Red, Sky Blue and White colours. 

**Why?**
The Parenting for Respectability programme colours are Green, Red, Sky Blue and White. We'd like to App theme to reflect these colours as part of its customisation.

**How?**
The current theme can be viewed via this link: https://parenting-for-respectability.web.app/template/home_screen

Below are examples of the updated App theme when implemented:
![pfr theme 1](https://github.com/IDEMSInternational/parenting-app-ui/assets/7933992/63833e39-2316-4a47-865e-4852b3588aaa)
![pfr theme 2](https://github.com/IDEMSInternational/parenting-app-ui/assets/7933992/45513ecf-2ce1-4d9a-822b-5019e7d28c71)
![pfr theme 3](https://github.com/IDEMSInternational/parenting-app-ui/assets/7933992/10015f57-a583-42c8-9032-d9ef6a66db9c)

**Other details**
The App figma designs can be viewed on this Figma link: https://www.figma.com/file/cQrhtErWGETatkqioXcujG/Parenting-for-Respectability-App-designs?type=design&node-id=0-1&mode=design&t=rpGZDbQSXycuJ4ML-0

**Comment by esmeetewinkel** [comment]
@laetitiaCA Could you upload any image of the PfR colours on which these designs are based? I am aware of the logo below, but this doesn't have sky blue. 

![pfr_latest_logo](https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/1ff1e296-a953-4eff-8930-ed2205632a48)

**Comment by esmeetewinkel** [comment]
[Orli recommended previously](https://github.com/IDEMSInternational/parenting-app-ui/issues/2101#issuecomment-1755607295) against using red and green because they have connotations of warnings/alerts. I assume we will ignore this in this case because these colours are used in the logo, but maybe still something to keep in mind when using them on buttons
