### ISSUE TITLE
Appetize action available on content repos

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2182]
**Details**
Make the test-appetize action available on content repos. This would enable content authors to test android assets (without being set up on android studio) and other functionalities such as notifications, share, download

**Comment by jfmcquade** [comment]
I think this may have been closed by #2200. @ChrisMarsh82 have we tested the functionality since merge do you know?

**Comment by esmeetewinkel** [comment]
I can't see the action/label on content repos, see for instance https://github.com/IDEMSInternational/plh-facilitator-app-zm-content/pull/42

**Comment by esmeetewinkel** [comment]
Outstanding task is stated in issue https://github.com/IDEMSInternational/parenting-app-ui/issues/2258, closing here
