### ISSUE TITLE
[BUG] Favicon override not showing, instead seeing default trefoil

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2207]
**Describe the bug**
I tried [including the custom favicon in the debug deployment](https://github.com/IDEMSInternational/app-debug-content/pull/50) (pointing it at `master` rather than the latest code release), following the instructions from https://github.com/IDEMSInternational/parenting-app-ui/pull/2192. However, I'm only able to see the default IDEMS trefoil icon, which was merged in https://github.com/IDEMSInternational/parenting-app-ui/pull/2203.

When opening the file `config.ts` in the debug deployment repo in VS Code, I see the problem `Property 'favicon_asset' does not exist on type 'IDeploymentConfig'`

**App version**
`debug` deployment v0.1.2.9

**To Reproduce**
Go to https://idems-debug.web.app/

**Screenshots and videos**
<img width="958" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/b30b8c11-ef2b-4448-822a-83a6b5ef666a">

<img width="631" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/0eb2638e-eab0-4b33-9815-d4d7af762250">

<img width="952" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/f83189c1-549c-424c-92bf-ae46bbfe5df1">

**Comment by jfmcquade** [comment]
Woops, the changes merged to the debug deployment didn't reflect the up-to-date code from #2192.
See this new PR for the debug deployment config: https://github.com/IDEMSInternational/app-debug-content/pull/51
And for experimenting locally, the property assignment is now with this line: `config.web.favicon_asset = "images/icons/favicon.svg";` (note `.web`)

**Comment by esmeetewinkel** [comment]
Thanks @jfmcquade, working now!
