### ISSUE TITLE
[BUG] build_android in Release to Google Play action fails

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2214]
**Describe the bug**
Release to Google Play action [fails](https://github.com/IDEMSInternational/plh-kids-app-tz-content/actions/runs/8100035947) when ran from the latest release, v0.16.24. This is on the `plh_kids_tz` deployment (which has no prior releases)

<img width="930" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/1024405b-9f97-4687-9d32-4a689ea8c042">

I tried pointing the repo at the previous release [v0.16.23](https://github.com/IDEMSInternational/plh-kids-app-tz-content/actions/runs/8100246538) and at [master](https://github.com/IDEMSInternational/plh-kids-app-tz-content/actions/runs/8099880544), but both fail.

**Comment by ChrisMarsh82** [comment]
This was an issue with the secrets. Fixed now
