### ISSUE TITLE
Crash in one flow causes the next flow not to launch

### ISSUE THREAD

**Issue by michaelclapham** [IDEMSInternational/parenting-app-ui#230]
Crash in one flow causes the next flow not to launch

**Comment by chrismclarke** [comment]
Recommend adding some sort of init/reset function that can be used when first initialised but also after any flow completion (where completion is for the full flow stack in case of linked flows). Ideally this should all be handled within the service, but as a fallback we could also call in chat page lifecycle events to make sure things have been setup/torn-down appropriately between navigation

**Comment by michaelclapham** [comment]
Closing as chat no longer being used
