### ISSUE TITLE
Feedback Points (to be organised)

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#279]
Here's a couple of issues that came up between December and today from the content/excel authoring side.
1.	Printing icons in text 
The content team would like to be able to print an icon in-line inside a message text (e.g. “mark your STAR <icon>”). 
DS suggestion: keep <icon> in message_text column, attach the image in the media column.

2.	Media aliases
DS suggested in December that images that are used multiple times (e.g. emojis, character emotions) should not be called by their file location, but instead by some core term. CC suggested to use the suffix _alias for this.

3.	Guides
I think there was a bit of a rush in December on managing the two guides. How is the choice of guide stored currently? Is this hardcoded? Do we need to figure out how to author this from excel?

4.	Printing how often habits have been recorded
The content team would like to be able to print how often a certain habit has been recorded within the last week (or any number of days) (e.g. “You’ve marked X praises in your STAR habits”). 

5.	Story mode
This discussion came up in December but was pushed forward. DS and I created an example sheet (example_story) using begin_slide and end_slide. This doesn’t yet work in the app.

**Comment by michaelclapham** [comment]
Opened https://github.com/IDEMSInternational/parenting-app-ui/pull/281 to address 1 and 5
