### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by michaelclapham** [IDEMSInternational/parenting-app-ui#317]
Create a countdown timer component using the following inputs

- timer_title: Text to show on top right of timer. (default "Timer")
- help: Link to open for help on clicking question mark button
-  timer_duration: Timer duration in minutes (default 10)
-  timer_duration_extension: (default 1)

Clicking the button on the bottom right with +1 in it should increase the time on the timer by the timer_duration_extension
When paused you should be able to change the time (see [timesolutely ](https://play.google.com/store/apps/details?id=com.timesolutely.presenter&hl=en&gl=US)app for example).

![Frame 1008](https://user-images.githubusercontent.com/3285072/108549041-8dad8000-72e4-11eb-95e6-d43fcff57a0c.png)

See frame in Figma: https://www.figma.com/file/ICMgnKW1UsF0Y1mUQnlunE/Designs-for-developers-V.2?node-id=46%3A1

Please create this timer component in the src/app/shared/components/template/components folder for now.

**Comment by smborio** [comment]
Final parameters:
* title - Text to show on top left of timer. (default "Timer")
* help - Link to open for help on clicking question mark
* duration - Timer duration in minutes (default 10)
* duration_extension - (default 1)

Will add a link to spreadsheet soon.
