### ISSUE TITLE
Number picker component

### ISSUE THREAD

**Issue by michaelclapham** [IDEMSInternational/parenting-app-ui#327]
Component for picking a number or a number range by pressing plus or minus buttons to either side of the number or range.

Optional title on top of picker.

![Group 27](https://user-images.githubusercontent.com/3285072/109979012-5aacb880-7cf6-11eb-8c23-9e2dd13c5530.png)

Component parameters:
- title: Adults
-  start_value: default 0. Minimum value that can be selected
- end_value: default to be defined. Maximum value that can be selected
- category_list:  empty by default. e.g 0-20; 21-25; 26-30; 30-40; 40-55; 55+
- category_size: 1 (for selecting a single number) or any positive integer for selecting a range (eg a category_size of 5 shows 21 - 25). Only consider this if category_list is empty.  

if 1 -> start_value, start_value +1, start_value+2, ..., end_value. if >1 -> “start_value - start_value+category_size-1”,”start_value+category_size - start_value+2*category_size-1”, “start_value+2*category_size - start_value+3*category_size-1”,...

- first_display_term: index for element in the list (in the case of 21 - 25 the value would be 5 as it is the 5th element in the list) starting with 1 (first element in list by default) 
-size: small / normal (this will determine whether it’s the short version or the tall version when there is a title)

**Comment by smborio** [comment]
We did a bit more work on this. the component parameters should be:

* d
