### ISSUE TITLE
Home screen tiles

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#335]
- Tiles should be clickable all over, also on the image. 
- The image should only overlap the tile border on the top (so the left-hand-border of the image fits within the tile).
- The text and images should be read from this core template
https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=646539876
where the global variables are set in this top template
https://docs.google.com/spreadsheets/d/1qNzL5selRW2Pzu74UAj7rz6d-blAnhQodm-dC1uChMI/edit#gid=0

![Screenshot](https://user-images.githubusercontent.com/74557272/110641191-9db0d500-81a9-11eb-955a-333f38374046.jpeg)

**Comment by michaelclapham** [comment]
Reopening as this  need to be done via template, not home_screen flow type
