### ISSUE TITLE
Weekly Workshops Screen

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#351]
This issue gives a specification of the screen that appears when clicking the "Weekly Workhops" tile on the home screen. 

![image](https://user-images.githubusercontent.com/74557272/111324132-67b89880-8662-11eb-8016-a027498a0ca0.png)

Corresponding spreadsheet: [weekly_workshops](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=1673198843)
Expansion box spreadsheet: [workshop_expansion](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=67642764) (there will be an instance of this spreadsheet for every workshop)
Global variables set in: [workshop_titles](https://docs.google.com/spreadsheets/d/1FXmKOQh-7iqi5JAYmJEQeqa-7C2ISpY4yLghFUV5md0/edit#gid=0)

 Following the screen top to bottom, left to right, this involves the following things:
1. title
2. help (clickable icon). Should read from its action_list what to do.
3. options button. Should read from its action_list what to do.
4. quick start tile (might be hidden).  Will be associated to a campaign.
5. A stepper that contains the ordered sequence of workshops as items. Each item in the stepper is clickable.  Should read from its action_list what to do, i.e. expanding the corresponding workshop_expansion. 
6. Inside any workshop_expansion, there is a display group with two tiles, each clickable using action_list, image read from the parameter_list. There are two buttons.
7. Each stepper item functions as a progress bar: fills up according to the proportion of workshop_activities of that workshop that have been completed, e.g. if 6 out of 9 have been completed the bar is 2/3 filled (blue).
8. Locked workshops have a lock icon, unlocked workshops have no icon, completed workshops have a tick. The circle is white when no content of that workshop has been completed, otherwise it is filled (blue).

**Comment by michaelclapham** [comment]
I think the options screen is sufficiently complex that it warrants it's own issue.

I also think the creation of the template component for the workshops accordion is self contained enough for it's own issue.

We probably want more detail on the behaviour for the quick start button.
