### ISSUE TITLE
Create a new action: set_theme

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#509]
To change between themes we will use the action set_theme on completion of an activity where the active/passive theme ends. The action list of the template will include completed | set_theme: active or completed | set_theme: passive respectively. Currently the only difference between active and passive themes is the background colour and the colour behind the banner/top image. The default should be passive.

We added this as comments in the self-care workshop: https://docs.google.com/spreadsheets/d/17lfsNZGb_3KYiMudc5SoxEj16uWxABrVKKW-4BAiLoA/edit#gid=0&range=G2

**Comment by egor-mir** [comment]
Add display group banner that will change based on set_theme value

**Comment by smborio** [comment]
and also background as well
