### ISSUE TITLE
style for left and right arrow button

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#538]
We need a new style for a button with a right or left arrow as per the [style guide figma](https://www.figma.com/file/ReyhcH2mKEu607xqWalvn8/Style-Guide?node-id=0%3A1) and the image below. 

![image](https://user-images.githubusercontent.com/46322225/114409567-7b441a00-9ba2-11eb-9341-3ffe1641f090.png)

We should have 2 styles for each pair of arrows, with the navigation and the information gradients. 
Style names should be left_arrow_navigation and right_arrow_navigation, and left_arrow_information and right_arrow_information

**Comment by egor-mir** [comment]
left_arrow information 
right_arrow navigation
left_arrow information
right_arrow information
