### ISSUE TITLE
two_columns_images style in dg has wrong heights for boxes

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#876]
The two_columns_images style for display grous is not working as expected. It should calculate the size of the boxes where the images are and ensure all have the same height. 
The relevant PR that creates this style is https://github.com/IDEMSInternational/parenting-app-ui/pull/873
The issue can be seen in image below, where the box where the IDEMS logo sits has different height as the other ones (feature_two_columns_images template):
![image](https://user-images.githubusercontent.com/46322225/123258718-952ba280-d4eb-11eb-8386-39dbffa8d9a6.png)

**Comment by zulkifelff** [comment]
Template Name: feature_two_columns_images_2

![Screenshot_true](https://user-images.githubusercontent.com/45070594/129707656-050fb3fa-cbab-4b87-8eb1-34a2c65d0ec3.png)

**Comment by zulkifelff** [comment]
Template Name: feature_two_columns_images

![Screenshot_true_2](https://user-images.githubusercontent.com/45070594/129710251-98c6c55a-1759-4d3d-9250-123ea774963e.png)

**Comment by zulkifelff** [comment]
@EsmeeIDEMS , If this seems okay I can create PR for this code.

Grid CSS Layout has been introduced in this instead of flex in order to have the same height.

**Comment by EsmeeIDEMS** [comment]
This looks good to me.

**Comment by ChrisMarsh82** [comment]
@zulkifelff If an odd number of logos then the last logo should be centered
