### ISSUE TITLE
[FEATURE] generate JSONs with app content data

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#906]
**What?**
Need data files (templates, data lists, globals and tours) in the folder packages\plh-data\data\data_list to be exportable in JSON format. 

**Why?**
The data files are used to generate content for translation and content review documents through scripts in other repos. The scripts read JSON files and before recent merges these files were similar enough to JSONs to deal with manually, but now there are too many differences (eg no double quotes on keys, commas after last elements of arrays, etc).

**How?**
It could be done through the content sync or through a new script that generates the JSONS and dumps them in a folder (preferable).

**Comment by chrismclarke** [comment]
@smborio - Can this now be closed following the work done in #916 or is there anything else needed?

**Comment by smborio** [comment]
@chrismclarke this is perfectly fine for now. If another need arises I'll create a new issue.
