### ISSUE TITLE
[BUG] Not receiving notifications

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#911]
**Describe the bug**
Notifications are still not being sent. I tested this with the app in my phone and could not find any setting that disables the app's notifications, reinstalling, and a few other things and can't find any reason why I'm not getting them. Users testing the app never got notifications either.

**App version**
0.10.3

**To Reproduce**
I left the app closed for over a week after resetting it, and after uninstalling it. The inactive_0 and inactive_1 notifications in [m_inactive_data](https://docs.google.com/spreadsheets/d/1RztJVUiuQZhXLN5lI0BUWcDqL9sBAz8_MbQwbWvfNb4/edit#gid=2010298881) should have been sent.

**Debug Template**
Not quite a debug template but the sheet [m_inactive_data](https://docs.google.com/spreadsheets/d/1RztJVUiuQZhXLN5lI0BUWcDqL9sBAz8_MbQwbWvfNb4/edit#gid=2010298881) demonstrates the way notifications for first app install and 7 weeks of inactivity are defined.

**Additional context**
Better testing for notifications would be great. An issue about this will follow up soon.

**Comment by EsmeeIDEMS** [comment]
Both @chrismclarke and Santiago have now reported receiving push notifications, so I'm closing this issue.
