### ISSUE TITLE
[BUG] Text in tiles inside a two_columns display group should be vertically centred. 

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#926]
**Describe the bug**
If you have a display group with style two_columns that has tiles with style image_text, the height of the tiles should all be the same, calculated according to the 'tallest' tile. The text in the tiles should then be vertically centred rather than at the top. 

**App version**
0.10.2

**To Reproduce**
You can see this bug by going to Home -> Parent Library -> Essential tools or looking at the debug template below.

**Template Name**
[parent_centre_essential_tools](https://docs.google.com/spreadsheets/d/1G0vehNt2KV8cDpyiqa1YT2rl2wQllKNA2w0246sHrdQ/edit#gid=811193770).

**Debug Template**
[debug_tile_text](https://docs.google.com/spreadsheets/d/1Y1pMWgVpJEXiJSpK8MCVKdjEwIdS3pzgHJM6A8PadeE/edit#gid=1916689711).

**Comment by ehmadzubair** [comment]
This will be fixed with #927

**Comment by ChrisMarsh82** [comment]
Closing as will be done in #927
