### ISSUE TITLE
[BUG] Tiles in a two_columns display group should have the same height

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#927]
**Describe the bug**
If you have a display group with style two_columns that has tiles with style image_text, the height of the tiles should all be the same, calculated according to the 'tallest' tile. Currently, this is not the case. 

**App version**
0.10.2

**To Reproduce**
You can see this bug by going to Home -> Parent Library -> Essential tools or looking at the debug template below.

**Template Name**
[parent_centre_essential_tools](https://docs.google.com/spreadsheets/d/1G0vehNt2KV8cDpyiqa1YT2rl2wQllKNA2w0246sHrdQ/edit#gid=811193770).

**Debug Template**
[debug_tile_text](https://docs.google.com/spreadsheets/d/1Y1pMWgVpJEXiJSpK8MCVKdjEwIdS3pzgHJM6A8PadeE/edit#gid=1916689711).

**Comment by zulkifelff** [comment]
Text Tiles usually has Image with Text. We have two different types of text types here that can be configured with keys 'first_line_text' and 'second_line_text'. After discussing it with Chris Clark, we have introduced scroll within the text. 

The height of the tiles was specified in CSS and can be altered based upon screen size (Media Query), which has been updated

Examples are as follow:

![debug_tile_text_2](https://user-images.githubusercontent.com/45070594/129177750-988a2fab-efde-49b7-91b1-8f66c10908f6.png)
![debug_tile_text_1](https://user-images.githubusercontent.com/45070594/129177756-385fe3b9-fd0c-4e3a-ac8a-af15fe9dfcd2.png)


If this is acceptable, I can lock the code and create PR against that.

**Comment by ehmadzubair** [comment]
@EsmeeIDEMS

**Comment by ehmadzubair** [comment]
@zulkifelff we will need to look into the CSS Grid Layout for this.

**Comment by EsmeeIDEMS** [comment]
- I'm happy with the size of the tiles (all the same height, indicated by the longest text).
- I'd prefer not to have a scroll within the tile. There will usually be a scroll on the page already, and I'm worried that another scroll within the tile is too confusing for users.
- Can the text be vertically centered within the tile? So the longest text indicates the height of the "text-section" of all tiles (as it does in your example), and the text on every tile is vertically centered within the "text-section". (See attached image)
<img width="163" alt="tile text centering" src="https://user-images.githubusercontent.com/74557272/130422937-3a1fffae-91e5-4c9c-911b-2da350eab9f3.png">

**Comment by ChrisMarsh82** [comment]
Linked to #926

**Comment by zulkifelff** [comment]
@EsmeeIDEMS , Changing the design to a GRID-based layout so that we can adjust heigh based upon the longest tile. The finalized results will be shared here. With that, the scroll within the tile will be removed.

**Comment by zulkifelff** [comment]
![Pixel2XL](https://user-images.githubusercontent.com/45070594/131468211-7c4fb1d3-6428-4e70-8252-3579ad6db4e4.png)

![MotoG4](https://user-images.githubusercontent.com/45070594/131468244-41ebb381-a16f-4d0e-aa63-ea61a9c19d0f.png)

**Comment by EsmeeIDEMS** [comment]
Thanks, this looks good for now.
