### ISSUE TITLE
[BUG] Toggle bar component styling got messed up

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#928]
**Describe the bug**
After merging some PRs (not sure which ones) the styling in the toggle bar component got messed up for some reason. See the screenshots below for what it is currently and what it should be.

**Debug Template**
[feature_toggle_bar](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=550703021)

**Screenshots and videos**
What they look like currently (in [feature_toggle_bar](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=550703021)):
<img src="https://user-images.githubusercontent.com/46322225/127465203-c9b9804c-e116-46b9-978d-bdcbec10aa04.png" width="300px">
What they should look like (they looked like this at some point in the past):
<img src="https://user-images.githubusercontent.com/46322225/127465573-fe6495d2-a536-4459-bb87-d152ecb3d973.png" width="700px">

**Comment by zulkifelff** [comment]
Stylesheet associate with this toggle component is 'toggle-bar.scss' , Update that particular stylesheet in order to create a similar User Experience .

The result is as follow:

![feature_toggle_bar](https://user-images.githubusercontent.com/45070594/129178724-d1986a7b-b42b-481d-adf8-315127200a79.png)

The updated stylesheet will cater toggle-bar with icons and without icons as well. If this seems okay, I will create PR for that particular change.

**Comment by zulkifelff** [comment]
@EsmeeIDEMS

**Comment by ehmadzubair** [comment]
@zulkifelff This looks good. Let's have a PR for this

**Comment by EsmeeIDEMS** [comment]
This looks great. One comment: The cross and tick icons provided by our designer have a slightly different style, find the svg files here: 

https://drive.google.com/file/d/100RoaUaG26cPMdcd9aUDX5ewbH_UlkmT/view?usp=sharing
https://drive.google.com/file/d/1YbKPSoGCWVQyiV2qut9_NsH3gNb3NETl/view?usp=sharing

(which are very similar to the *checkmark* and *close-outline* icons in the open-source icon library https://ionic.io/ionicons)

I'd suggest one of following solutions:
1. Keep the current syntax in the spreadsheet, but use the icons the designer provided.
2. Change the syntax in the spreadsheet, adding parameters (e.g. *true_icon_src* and *false_icon_src*, and renaming the parameter *show_tick_and_cross* to *show_icons*) to specify which icons should be used. As usual, these parameters should work with both names from the ion-icon library (e.g. true_icon_src: checkmark) and with file paths in the plh_assets folder (e.g. true_icon_src: plh_images/icons/tick.svg).

**Comment by zulkifelff** [comment]
Adopting provided scalable vector graphics as icons.

![Screenshot (149)](https://user-images.githubusercontent.com/45070594/130607157-c110de1d-7f5c-4571-a718-4d0c62cefca5.png)

**Comment by ChrisMarsh82** [comment]
@zulkifelff that looks good.
