### ISSUE TITLE
Removing hard-coded pages (from old menu)

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#929]
**Details**
Until PR #923 the side menu had all its content hard-coded. The PR means that things are now templated and we should remove the hardcoded elements. The relevant files are:
1. src\app\pages\about\about.page.html
2. src\app\pages\app-terms\app-terms.page.html
3. src\app\pages\privacy\privacy.page.html
4. src\app\pages\settings\settings.page.html

Note: some of these files include functions that were there for internal functionality of the menu or its components (eg routing functions in item 4) and they all have ts and css files that will probably no longer be needed. (The reset_app function is needed as it is now an action in the app. It will probably have to be moved elsewhere if these files are being completely removed and it definitely needs to be reviewed and expanded on in the near future. I don't know any other details off the top of my head.)

**Comment by zulkifelff** [comment]
@EsmeeIDEMS 
Need a little bit of help from your side on this issue especially related to resetting the application.

**Comment by ChrisMarsh82** [comment]
@ehmadzubair I will speak to you about this.
