### ISSUE TITLE
Efficiency Improvements - content sync

### ISSUE THREAD

**Issue by smborio** [IDEMSInternational/parenting-app-ui#930]
**Details**
Currently we have two ways of syncing content from the google spreadsheets:
1. Full sync: (through `npm run scripts sync-plh-content`). This downloads all the files, interprets them, runs a number of checks and creates JSON outputs, mainly for translation, possibly other things as well.
2. Single file sync: (through `npm run scripts sync-single -- file_name`). This downloads only the specified file, if it was already downloaded previously, and runs everything else the full sync script runs.

We would welcome the following efficiencies:
1. Separate the creation of the output JSONs through a new independent script and remove this from the sync process.
2. Be able to just sync content (full or single) without running tests (this would allow us to make a small change and visualise it in the app quickly)
3. Be able to sync a single template/global/tour/data_list rather than a file. In this scenario, only the relevant data file would be updated; currently the syncing updates several files and the build has to happen several times before we can see the outcomes in the local app. 

This could be achieved with several scripts that do different things and one overarching script that contains all the syncing aspects or maybe have a way of selecting which processes we want in the existing scripts.

**Comment by chrismclarke** [comment]
Following discussion with David we will move this to a backlog issue as optimisations suggested would require quite a few other changes to the backend scripts first. Particularly, as output files are compiled across templates (e.g. all templates of a particular flow type are merged together), reprocessing an incremental change would involve reading in the output files which isn't ideal.

In the shorter term recommendations:

- Remove old template files not longer needed to reduce number of files processed
- Add flow subtypes to more files (particularly example/debug) to allow future partial sync across flow type
