### ISSUE TITLE
[FEATURE] - E2E Testing System

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#938]
**What?**
Add an automated testing system that can be build out to carry out core app functionality tests either as integration tests or end-to-end.

**Why?**
Make it easier to identify breaking changes to updates, reduce amount of manual testing performed.

**How?**
My personal recommendation would be [cypress](https://www.cypress.io/), but open to suggestions.
We would start with example templates, creating a test that loads each example and confirms content is as expected (e.g. if required to input a value or click a button, the correct text is shown at the end)

**Other details**
Would also be good to be systematic in the way we use content to indicate if information is displayed correctly or not (e.g. adding a column that tracks test variable expected state, or simply words like 'Pass' and 'Fail' if all criteria are satisfied correctly

**Comment by ehmadzubair** [comment]
Cypress looks like the better choice here although I've heard good things about [mabl](https://www.mabl.com/) too

**Comment by chrismclarke** [comment]
Interesting, haven't tried mabl before, will be sure to check it out.  The useful thing about cypress is the test runner is open-source, so fits our goals quite well. They do offer a hosted dashboard to view published test runs which we may eventually want, but fortunately they also provide for free to open source projects.
