### ISSUE TITLE
Improve the Notification testing workflow

### ISSUE THREAD

**Issue by ehmadzubair** [IDEMSInternational/parenting-app-ui#948]
**Details**
There is no easy way to test notifications workflow right now. The only point where they can be tested is from the Campaigns screen. 

It would be ideal to have a workflow that can be tested on the browser as well because testing it on a physical device is very inefficient.

**Comment by ehmadzubair** [comment]
@chrismclarke

**Comment by chrismclarke** [comment]
For some context, notifications are sent via the [Capacitor Local Notifications Plugin](https://capacitorjs.com/docs/apis/local-notifications). 

According to the docs they are only available when running physically on Android device, but the following issue suggests they have some potential support in browser and ios: `https://github.com/ionic-team/capacitor/issues/1355`, although this issue on stackoverflow suggest maybe only in limited browsers/ways: https://stackoverflow.com/questions/63155707/capacitor-local-notification-in-pwa-with-ionic-5.

So I think the first challenge is to see if it's even possible to get things working in a web browser. I'd recommend adding a new `notifications` feature folder with a simple testing page with a couple buttons to try and trigger the local notification sending. This should definitely work to manually trigger a notification on device, might work on web preview build (not sure if depends on service worker or not), and probably won't work when developing on localhost.

From there we can either try to debug, or possibly put together a very rough mock service that can mimic the functionality when running locally (e.g. showing an alert/popup with the notification content when the schedule hits).
