### ISSUE TITLE
Tour improvements

### ISSUE THREAD

**Issue by EsmeeIDEMS** [IDEMSInternational/parenting-app-ui#967]
**Details**

- [ ] #969
- [ ]  Tour sheets are currently written in HTML (they are in fact the only sheet that use HTML). We should probably update the authoring syntax to be in line with the rest of the app spreadsheets.

**Screenshots and videos**
![image](https://user-images.githubusercontent.com/74557272/130604016-bb1a5de3-317d-430d-8c6a-355d2cc40d65.png)

**Comment by chrismclarke** [comment]
As discussed on calls, I'll take a look at this one when I get a chance to see if there's a reasonable way to quickly implement the existing template system with tour rows
